// src/pages/LoginSignupPage.tsx
import LoginSignup from '../components/login/LoginSignup';
import './LoginSignupPage.css';

export default function LoginSignupPage() {
  return (
    <div className="login-page-container">
      <LoginSignup />
      <div className="login-page-background">
        <img src="/assets/images/login-background-images/background.svg" alt="background" />
      </div>
    </div>
  );
}

// src/app/login/login-signup-page/login-signup-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login-signup-page',
  templateUrl: './login-signup-page.component.html',
  styleUrls: ['./login-signup-page.component.css']
})
export class LoginSignupPageComponent {

}

<app-login-signup></app-login-signup>

  <div class="background">
    <img src="/assets/images/login-background-images/background.svg" alt="background">
  </div>

  <!--  -->
