// src/app/liqueur/liqueur-title/liqueur-title.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-title',
  templateUrl: './liqueur-title.component.html',
  styleUrls: ['./liqueur-title.component.css']
})
export class LiqueurTitleComponent {

}

<div class="container">
    <img src="/assets/images/liqueur-images/liqueur-title.jpg" alt="liqueur-image" class="liqueur-image">
    <p class="title">LIQUEUR</p>
</div>

// src/components/liqueur/LiqueurTitle.tsx
import './LiqueurTitle.css';

export default function LiqueurTitle() {
  return (
    <div className="liqueur-title-container">
        <img src="/assets/images/liqueur-images/liqueur-title.jpg" alt="liqueur-image" className="liqueur-image" />
        <p className="title">LIQUEUR</p>
    </div>
  );
}
