// src/app/liqueur/liqueur-process/liqueur-process.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-process',
  templateUrl: './liqueur-process.component.html',
  styleUrls: ['./liqueur-process.component.css']
})
export class LiqueurProcessComponent {

}

<div class="container">
    <p class="title">The Mystical Art of Liqueur Crafting:</p>
    <div class="content">

        <p class="title-baileys">BAILEYS</p>
        <p class="content-baileys">Imagine the lush green fields of Ireland, where cows graze freely, producing the creamiest of milk. This milk, combined with rich Irish whiskey, forms the base of Baileys. Add a sprinkle of cocoa, a dash of vanilla, and a secret blend of ingredients, and you have a velvety drink that dances on your palate. Each sip is like a warm Irish hug, enveloping you in its creamy embrace. Sláinte! 🥃🍫🐄
            <br><br>    
            Ah, Baileys, the creamy dream that dances on the palate! The secret to its velvety texture lies in the meticulous blending of rich Irish dairy cream with the finest whiskey. The cream, sourced from the Emerald Isle's happy cows, is preserved naturally by the whiskey, ensuring no preservatives are needed. And for that hint of cocoa and vanilla? Well, that's a trade secret, whispered among the leprechauns of old. So, next time you sip this liquid silk, imagine the Irish meadows and the magic they brew!</p><br>

        <p class="title-cointreau">COINTREAU</p>
        <p class="content-cointreau">Venture into the sun-kissed orchards of Spain, where bitter and sweet orange peels are sun-drying, waiting to be transformed. These peels are then macerated and distilled to capture their vibrant essence. The result? Cointreau, a crystal-clear liqueur bursting with zesty orange notes. It's like sipping on liquid sunshine! 🍊☀️🍹
            <br><br>
            Dive deeper into the world of Cointreau, and you'll find yourself amidst sun-kissed orange orchards. This crystal-clear potion is crafted using a blend of sweet and bitter orange peels. But it's not just about tossing peels into alcohol. Oh no! The peels are carefully macerated to extract their essence, and then distilled to capture the pure, zesty spirit of the orange. Legend has it, on a moonlit night, you can hear the oranges whispering their citrusy secrets to the Cointreau makers.</p><br>

        <p class="title-amaretto">AMARETTO</p>
        <p class="content-amaretto">Journey to the heart of Italy, where the sweetest of almonds meet the bitterest of apricot kernels. These are combined with pure alcohol, burnt sugar, and a blend of aromatic herbs. The outcome? Amaretto, a sweet, almond-flavored liqueur that whispers tales of Italian romance with every sip. Saluti! 🥂🌰💋
            <br><br>
            Behind the sweet allure of Amaretto lies a tale of love and craftsmanship. Originating from Italy, its name literally means "a little bitter". But there's more sweetness here than bitterness. Made traditionally from bitter almonds or apricot pits, the core ingredient is infused in pure alcohol. Add a dash of sweet syrup, and voilà! But remember, every sip carries with it the warmth of Italian romance, where legends say it was crafted by a lovelorn maiden for her artist lover.</p><br>

        <p class="title-chambord">CHAMBORD</p>
        <p class="content-chambord">Step into the Loire Valley of France, where plump raspberries and blackberries are waiting to be plucked. These berries, along with honey, vanilla, and fragrant herbs, are infused into a spirit. The concoction is then matured in oak barrels. The finale? Chambord, a rich, fruity liqueur that's reminiscent of French royalty. Vive la France! 🍇👑🍷
            <br><br>
            Journey further into the heart of Chambord, and you'll find yourself amidst the lush berry fields of France's Loire Valley. This luxurious liqueur is a symphony of raspberries, blackberries, Madagascar vanilla, Moroccan citrus peel, honey, and cognac. Each ingredient is meticulously blended, creating layers of flavors that dance harmoniously on the tongue. It's said that sipping Chambord is like being serenaded by a French bard under a starry night.</p><br>

        <p class="title-sambuca">SAMBUCA</p>
        <p class="content-sambuca">Dive into the vibrant culture of Italy, where the star anise plant grows in abundance. Its seeds, with their licorice-like flavor, are distilled with wheat, sugar, and a bouquet of aromatic herbs. The potion? Sambuca, a clear, anise-flavored liqueur that's often served with a trio of coffee beans, representing health, happiness, and prosperity. Salute! 🌟☕️🥂
            <br><br>
            Delve deeper into the mystique of Sambuca, and you're transported to old Italian harbors under moonlit skies. This anise-flavored gem is often adorned with floating star anise seeds, looking like distant stars captured in a bottle. The aniseed is steeped in pure alcohol, with a touch of sugar to sweeten the night. And for those who like a spectacle, Sambuca is often flambéed, making it a drink truly touched by fire!</p><br>

        <p class="title-jagermeister">JAGERMEISTER</p>
        <p class="content-jagermeister">Wander into the mystical forests of Germany, where 56 different herbs, fruits, roots, and spices are gathered. These ingredients are ground, steeped in water and alcohol, and then aged in oak barrels for a year. The elixir? Jägermeister, a dark, complex liqueur that's a symphony of flavors in every shot. Prost! 🌲🍂🍻
            <br><br>
            Venture further into the enigmatic forest of Jägermeister, and you'll discover a blend of 56 different herbs, fruits, roots, and spices. From the gingery notes of galangal to the sweet warmth of cinnamon, each ingredient is macerated in water and alcohol, then aged in oak barrels. It's whispered among the trees that the recipe is known to only a select few, guarded as fiercely as a dragon guards its treasure. So, when you taste its complexity, know you're sipping on a potion crafted from nature's guarded secrets.</p><br>

        <p class="closing">The art of liqueur crafting is a journey through nature's bounty, a celebration of flavors, and a testament to human ingenuity. From the orchards of Spain to the forests of Germany, each bottle captures the essence of its origin, telling a story that's as rich as its taste. So, the next time you pour a glass, take a moment to savor the history, the craft, and the love that goes into every drop. Cheers to the world of liqueurs, where magic is bottled! 🍾🌍🥂</p>
    </div>
</div>

// src/components/liqueur/LiqueurProcess.tsx
import './LiqueurProcess.css';

export default function LiqueurProcess() {
  return (
    <div className="liqueur-process-container">
        <p className="liqueur-process-title">The Mystical Art of Liqueur Crafting:</p>
        <div className="liqueur-process-content">

            <p className="title-baileys">BAILEYS</p>
            <p className="content-baileys">Imagine the lush green fields of Ireland, where cows graze freely, producing the creamiest of milk. This milk, combined with rich Irish whiskey, forms the base of Baileys. Add a sprinkle of cocoa, a dash of vanilla, and a secret blend of ingredients, and you have a velvety drink that dances on your palate. Each sip is like a warm Irish hug, enveloping you in its creamy embrace. Sláinte! 🥃🍫🐄
                <br/><br/>    
                Ah, Baileys, the creamy dream that dances on the palate! The secret to its velvety texture lies in the meticulous blending of rich Irish dairy cream with the finest whiskey. The cream, sourced from the Emerald Isle's happy cows, is preserved naturally by the whiskey, ensuring no preservatives are needed. And for that hint of cocoa and vanilla? Well, that's a trade secret, whispered among the leprechauns of old. So, next time you sip this liquid silk, imagine the Irish meadows and the magic they brew!</p><br/>

            <p className="title-cointreau">COINTREAU</p>
            <p className="content-cointreau">Venture into the sun-kissed orchards of Spain, where bitter and sweet orange peels are sun-drying, waiting to be transformed. These peels are then macerated and distilled to capture their vibrant essence. The result? Cointreau, a crystal-clear liqueur bursting with zesty orange notes. It's like sipping on liquid sunshine! 🍊☀️🍹
                <br/><br/>
                Dive deeper into the world of Cointreau, and you'll find yourself amidst sun-kissed orange orchards. This crystal-clear potion is crafted using a blend of sweet and bitter orange peels. But it's not just about tossing peels into alcohol. Oh no! The peels are carefully macerated to extract their essence, and then distilled to capture the pure, zesty spirit of the orange. Legend has it, on a moonlit night, you can hear the oranges whispering their citrusy secrets to the Cointreau makers.</p><br/>

            <p className="title-amaretto">AMARETTO</p>
            <p className="content-amaretto">Journey to the heart of Italy, where the sweetest of almonds meet the bitterest of apricot kernels. These are combined with pure alcohol, burnt sugar, and a blend of aromatic herbs. The outcome? Amaretto, a sweet, almond-flavored liqueur that whispers tales of Italian romance with every sip. Saluti! 🥂🌰💋
                <br/><br/>
                Behind the sweet allure of Amaretto lies a tale of love and craftsmanship. Originating from Italy, its name literally means "a little bitter". But there's more sweetness here than bitterness. Made traditionally from bitter almonds or apricot pits, the core ingredient is infused in pure alcohol. Add a dash of sweet syrup, and voilà! But remember, every sip carries with it the warmth of Italian romance, where legends say it was crafted by a lovelorn maiden for her artist lover.</p><br/>

            <p className="title-chambord">CHAMBORD</p>
            <p className="content-chambord">Step into the Loire Valley of France, where plump raspberries and blackberries are waiting to be plucked. These berries, along with honey, vanilla, and fragrant herbs, are infused into a spirit. The concoction is then matured in oak barrels. The finale? Chambord, a rich, fruity liqueur that's reminiscent of French royalty. Vive la France! 🍇👑🍷
                <br/><br/>
                Journey further into the heart of Chambord, and you'll find yourself amidst the lush berry fields of France's Loire Valley. This luxurious liqueur is a symphony of raspberries, blackberries, Madagascar vanilla, Moroccan citrus peel, honey, and cognac. Each ingredient is meticulously blended, creating layers of flavors that dance harmoniously on the tongue. It's said that sipping Chambord is like being serenaded by a French bard under a starry night.</p><br/>

            <p className="title-sambuca">SAMBUCA</p>
            <p className="content-sambuca">Dive into the vibrant culture of Italy, where the star anise plant grows in abundance. Its seeds, with their licorice-like flavor, are distilled with wheat, sugar, and a bouquet of aromatic herbs. The potion? Sambuca, a clear, anise-flavored liqueur that's often served with a trio of coffee beans, representing health, happiness, and prosperity. Salute! 🌟☕️🥂
                <br/><br/>
                Delve deeper into the mystique of Sambuca, and you're transported to old Italian harbors under moonlit skies. This anise-flavored gem is often adorned with floating star anise seeds, looking like distant stars captured in a bottle. The aniseed is steeped in pure alcohol, with a touch of sugar to sweeten the night. And for those who like a spectacle, Sambuca is often flambéed, making it a drink truly touched by fire!</p><br/>

            <p className="title-jagermeister">JAGERMEISTER</p>
            <p className="content-jagermeister">Wander into the mystical forests of Germany, where 56 different herbs, fruits, roots, and spices are gathered. These ingredients are ground, steeped in water and alcohol, and then aged in oak barrels for a year. The elixir? Jägermeister, a dark, complex liqueur that's a symphony of flavors in every shot. Prost! 🌲🍂🍻
                <br/><br/>
                Venture further into the enigmatic forest of Jägermeister, and you'll discover a blend of 56 different herbs, fruits, roots, and spices. From the gingery notes of galangal to the sweet warmth of cinnamon, each ingredient is macerated in water and alcohol, then aged in oak barrels. It's whispered among the trees that the recipe is known to only a select few, guarded as fiercely as a dragon guards its treasure. So, when you taste its complexity, know you're sipping on a potion crafted from nature's guarded secrets.</p><br/>

            <p className="closing">The art of liqueur crafting is a journey through nature's bounty, a celebration of flavors, and a testament to human ingenuity. From the orchards of Spain to the forests of Germany, each bottle captures the essence of its origin, telling a story that's as rich as its taste. So, the next time you pour a glass, take a moment to savor the history, the craft, and the love that goes into every drop. Cheers to the world of liqueurs, where magic is bottled! 🍾🌍🥂</p>
        </div>
    </div>
  );
}
