// src/app/liqueur/liqueur-types/liqueur-types.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-types',
  templateUrl: './liqueur-types.component.html',
  styleUrls: ['./liqueur-types.component.css']
})
export class LiqueurTypesComponent {

}

<div class="container">
    <p class="title">A Spirited Voyage: Liqueurs & Cordials Unveiled!</p>
    <div class="content">

        <p class="title-baileys">BAILEYS IRISH CREAM</p>
        <p class="content-baileys">Baileys is the harmonious marriage of robust whiskey and luscious cream from the emerald isles of Ireland. It's a gentle Irish lullaby for your senses, reminiscent of tales told by the fireplace on a cold winter's night. Every sip is a creamy dream, wrapping you in a blanket of warmth and comfort. It's the liquid silk with a hint of mischief you've been searching for!</p><br>

        <p class="title-cointreau">COINTREAU</p>
        <p class="content-cointreau">Cointreau captures the essence of French elegance. A radiant blend of sun-kissed oranges, it dances between bitter and sweet, creating a tantalizing tango on your tongue. It's the spirit of Parisian boulevards, romantic evenings, and the allure of twilight by the Seine. Truly, the orange zest you never knew you needed!</p><br>

        <p class="title-amaretto">AMARETTO</p>
        <p class="content-amaretto">Amaretto, whisked straight from the heart of Italy, is a serenade in liquid form. With its sweet almond embrace and subtle apricot whispers, it's like a moonlit gondola ride through the canals of Venice. A drink that sings of love, passion, and Italian summers. Bellissimo!</p><br>

        <p class="title-chambord">CHAMBORD</p>
        <p class="content-chambord">Chambord is the crown jewel of liqueurs, a regal raspberry rendezvous. Crafted with precision, it's a symphony of berries, vanilla, and herbs. It's the essence of French châteaux, lavish balls, and timeless elegance. Dive into this berry-infused dream and experience luxury in every sip.</p><br>

        <p class="title-sambuca">SAMBUCA</p>
        <p class="content-sambuca">Sambuca, the starry-eyed Italian dreamer, is an ode to anise. With its bold flavors and theatrical flair, it's a drink that's both a mystery and a revelation. It's the spirit of Italian piazzas, lively conversations, and the magic of Mediterranean nights. Let it serenade you with its licorice love affair!</p><br>

        <p class="title-jagermeister">JÄGERMEISTER</p>
        <p class="content-jagermeister">Jägermeister, from the heart of Germany, is a potion of 56 botanicals that dance in a mystical brew. It's a journey through enchanted forests, tales of valor, and age-old traditions. Every drop is a testament to craftsmanship, heritage, and the wild spirit of the German woods. Prost to adventures!</p><br>

        <p class="closing">From the rolling hills of Ireland to the bustling cafes of Italy, liqueurs and cordials are the vibrant threads that weave tales of cultures, traditions, and moments. They're not just drinks; they're experiences, memories, and stories waiting to be shared. So, embark on this flavorful odyssey, and let the world's elixirs regale you with their enchanting tales. To adventures, memories, and the magic in every bottle! 🍷🌌🍸</p>
    </div>
</div>

// src/components/liqueur/LiqueurTypes.tsx
import './LiqueurTypes.css';

export default function LiqueurTypes() {
  return (
    <div className="liqueur-types-container">
        <p className="liqueur-types-title">A Spirited Voyage: Liqueurs & Cordials Unveiled!</p>
        <div className="liqueur-types-content">

            <p className="title-baileys">BAILEYS IRISH CREAM</p>
            <p className="content-baileys">Baileys is the harmonious marriage of robust whiskey and luscious cream from the emerald isles of Ireland. It's a gentle Irish lullaby for your senses, reminiscent of tales told by the fireplace on a cold winter's night. Every sip is a creamy dream, wrapping you in a blanket of warmth and comfort. It's the liquid silk with a hint of mischief you've been searching for!</p><br/>

            <p className="title-cointreau">COINTREAU</p>
            <p className="content-cointreau">Cointreau captures the essence of French elegance. A radiant blend of sun-kissed oranges, it dances between bitter and sweet, creating a tantalizing tango on your tongue. It's the spirit of Parisian boulevards, romantic evenings, and the allure of twilight by the Seine. Truly, the orange zest you never knew you needed!</p><br/>

            <p className="title-amaretto">AMARETTO</p>
            <p className="content-amaretto">Amaretto, whisked straight from the heart of Italy, is a serenade in liquid form. With its sweet almond embrace and subtle apricot whispers, it's like a moonlit gondola ride through the canals of Venice. A drink that sings of love, passion, and Italian summers. Bellissimo!</p><br/>

            <p className="title-chambord">CHAMBORD</p>
            <p className="content-chambord">Chambord is the crown jewel of liqueurs, a regal raspberry rendezvous. Crafted with precision, it's a symphony of berries, vanilla, and herbs. It's the essence of French châteaux, lavish balls, and timeless elegance. Dive into this berry-infused dream and experience luxury in every sip.</p><br/>

            <p className="title-sambuca">SAMBUCA</p>
            <p className="content-sambuca">Sambuca, the starry-eyed Italian dreamer, is an ode to anise. With its bold flavors and theatrical flair, it's a drink that's both a mystery and a revelation. It's the spirit of Italian piazzas, lively conversations, and the magic of Mediterranean nights. Let it serenade you with its licorice love affair!</p><br/>

            <p className="title-jagermeister">JÄGERMEISTER</p>
            <p className="content-jagermeister">Jägermeister, from the heart of Germany, is a potion of 56 botanicals that dance in a mystical brew. It's a journey through enchanted forests, tales of valor, and age-old traditions. Every drop is a testament to craftsmanship, heritage, and the wild spirit of the German woods. Prost to adventures!</p><br/>

            <p className="closing">From the rolling hills of Ireland to the bustling cafes of Italy, liqueurs and cordials are the vibrant threads that weave tales of cultures, traditions, and moments. They're not just drinks; they're experiences, memories, and stories waiting to be shared. So, embark on this flavorful odyssey, and let the world's elixirs regale you with their enchanting tales. To adventures, memories, and the magic in every bottle! 🍷🌌🍸</p>
        </div>
    </div>
  );
}
