// src/app/liqueur/liqueur-overview/liqueur-overview.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-overview',
  templateUrl: './liqueur-overview.component.html',
  styleUrls: ['./liqueur-overview.component.css']
})
export class LiqueurOverviewComponent {

}

<div class="container">
    <p class="title">The Luscious Liqueur Legend:</p>
    <p class="content">In a realm where spirits danced and wines serenaded, there emerged a question: "How do we craft a drink that's both spirited and sweet, a potion that tells tales of ancient herbs and luscious fruits?" And so, in this vibrant tapestry of beverages, liqueurs and cordials made their grand entrance!<br>
        <br>
        These weren't just any ordinary drinks; they were the alchemists' dream. Fruits, once basking under the sun, dreaming of becoming the sweetest in the orchard, were chosen for a nobler cause. They thought, "Why not be immortalized in a bottle, where our essence can be savored for ages?" And thus, they became the soul of these enchanting elixirs.<br>
        <br>
        But the fruits had companions on this epic journey. Mystical herbs, plucked under moonlit nights, and exotic spices, traded from lands afar, joined the symphony. Together, they were steeped in spirits, absorbing their strength, yet softening their edges with sweetness. And then there was sugar – the sweet whisperer, ensuring every sip was a harmonious blend of strength and sweetness.<br>
        <br>
        As time wove its tales, these liqueurs and cordials traveled, from grand palaces to humble homes, leaving a trail of stories and memories. They became the secret ingredient in cocktails, the toast of celebrations, and the comforting sip on a cold night. And that, dear reader, is the legend of liqueurs and cordials, the drinks that captured the essence of nature and the artistry of man.
    </p>
</div>

// src/components/liqueur/LiqueurOverview.tsx
import './LiqueurOverview.css';

export default function LiqueurOverview() {
  return (
    <div className="liqueur-overview-container">
        <p className="liqueur-overview-title">The Luscious Liqueur Legend:</p>
        <p className="liqueur-overview-content">In a realm where spirits danced and wines serenaded, there emerged a question: "How do we craft a drink that's both spirited and sweet, a potion that tells tales of ancient herbs and luscious fruits?" And so, in this vibrant tapestry of beverages, liqueurs and cordials made their grand entrance!<br/>
            <br/>
            These weren't just any ordinary drinks; they were the alchemists' dream. Fruits, once basking under the sun, dreaming of becoming the sweetest in the orchard, were chosen for a nobler cause. They thought, "Why not be immortalized in a bottle, where our essence can be savored for ages?" And thus, they became the soul of these enchanting elixirs.<br/>
            <br/>
            But the fruits had companions on this epic journey. Mystical herbs, plucked under moonlit nights, and exotic spices, traded from lands afar, joined the symphony. Together, they were steeped in spirits, absorbing their strength, yet softening their edges with sweetness. And then there was sugar – the sweet whisperer, ensuring every sip was a harmonious blend of strength and sweetness.<br/>
            <br/>
            As time wove its tales, these liqueurs and cordials traveled, from grand palaces to humble homes, leaving a trail of stories and memories. They became the secret ingredient in cocktails, the toast of celebrations, and the comforting sip on a cold night. And that, dear reader, is the legend of liqueurs and cordials, the drinks that captured the essence of nature and the artistry of man.
        </p>
    </div>
  );
}
