// src/app/liqueur/liqueur-food/liqueur-food.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-food',
  templateUrl: './liqueur-food.component.html',
  styleUrls: ['./liqueur-food.component.css']
})
export class LiqueurFoodComponent {

}

<div class="container">
    <p class="title">Brews & Bites: A Culinary Symphony!</p>
    <div class="content">

        <div class="lager">
            <p class="title-lager">LAGER</p>
            <p class="vibe-lager">The Vibe: Golden sunsets, the gentle hum of a beachside cafe, and the promise of endless summer.</p>
            <p class="content-lager">Lager, with its crisp and refreshing notes, is the soundtrack to every summer memory. Dive into a seafood paella bursting with flavors, munch on a classic club sandwich, or relish a tangy tomato bruschetta. Lager's effervescence dances with these flavors, turning every meal into a sunlit fiesta!<br><br></p>

        <div class="ale">
            <p class="title-ale">ALE</p>
            <p class="vibe-ale">The Vibe: Rustic charm, the camaraderie of a pub, and tales told over amber pints.</p>
            <p class="content-ale">Ale, robust and full-bodied, is like a warm embrace on a chilly evening. Think spicy buffalo wings, hearty beef pies, or a spicy chorizo pizza. Ale's rich character melds with these robust dishes, making every bite a hearty high-five to your taste buds!<br><br></p>

        <div class="stout">
            <p class="title-stout">STOUT</p>
            <p class="vibe-stout">The Vibe: Snowflakes outside, a plush armchair, and the comforting aroma of home-cooked food.</p>
            <p class="content-stout">Stout, the deep and velvety poet of beers, is perfect for those introspective moments. Pair it with a slow-cooked lamb shank, a rich and gooey chocolate brownie, or a plate of blue cheese and figs. Stout's roasted notes elevate these dishes, making every bite a comforting caress.<br><br></p>

        <div class="ipa">
            <p class="title-ipa">INDIA PALE ALE (IPA)</p>
            <p class="vibe-ipa">The Vibe: A bustling street festival, vibrant colors, and the thrill of discovery.</p>
            <p class="content-ipa">IPA, the audacious adventurer, is all about the hops and the heat. Dive into a spicy Mexican taco, savor a tangy Thai curry, or bite into a fiery jerk chicken. IPA's boldness stands tall, turning every meal into a carnival of flavors!<br><br></p>

        <div class="pilsner">
            <p class="title-pilsner">PILSNER</p>
            <p class="vibe-pilsner">The Vibe: A rooftop soiree, twinkling city lights, and the clink of crystal glasses.</p>
            <p class="content-pilsner">Pilsner, the epitome of elegance, is all about the finer things in life. Indulge in a plate of sushi, savor a truffle-infused pasta, or enjoy a delicate salmon tartare. Pilsner's grace complements these dishes, making every bite a taste of luxury.<br><br></p>

        <div class="wheat-beer">
            <p class="title-wheat-beer">WHEAT BEER</p>
            <p class="vibe-wheat-beer">The Vibe: Lazy Sunday mornings, the rustle of newspapers, and the joy of a brunch spread.</p>
            <p class="content-wheat-beer">Wheat Beer, the cheerful brunch buddy, is all about lightness and zest. Delight in a fluffy Belgian waffle, a citrusy fruit salad, or a creamy quiche. Wheat Beer's playful bubbles turn every brunch into a sun-kissed celebration!<br><br></p>
        </div>

        <p class="closing">From sunlit beaches to cozy winter cabins, beer is the universal companion that celebrates every flavor, every moment, and every memory. Each brew, with its distinct personality, paints a vivid picture, turning meals into stories and bites into adventures. So, pop open a bottle, pour yourself a pint, and let the culinary journey begin. To the magic of malt, the beauty of barley, and the wonder of wheat! Cheers to the world on our plates and the brews in our glasses! 🍺🍴🎊</p>
    </div>
</div>

// src/components/liqueur/LiqueurFood.tsx
import './LiqueurFood.css';

export default function LiqueurFood() {
  return (
    <div className="liqueur-food-container">
        <p className="liqueur-food-title">Brews & Bites: A Culinary Symphony!</p>
        <div className="liqueur-food-content">

            <div className="lager">
                <p className="title-lager">LAGER</p>
                <p className="vibe-lager">The Vibe: Golden sunsets, the gentle hum of a beachside cafe, and the promise of endless summer.</p>
                <p className="content-lager">Lager, with its crisp and refreshing notes, is the soundtrack to every summer memory. Dive into a seafood paella bursting with flavors, munch on a classic club sandwich, or relish a tangy tomato bruschetta. Lager's effervescence dances with these flavors, turning every meal into a sunlit fiesta!<br/><br/></p>
            </div>

            <div className="ale">
                <p className="title-ale">ALE</p>
                <p className="vibe-ale">The Vibe: Rustic charm, the camaraderie of a pub, and tales told over amber pints.</p>
                <p className="content-ale">Ale, robust and full-bodied, is like a warm embrace on a chilly evening. Think spicy buffalo wings, hearty beef pies, or a spicy chorizo pizza. Ale's rich character melds with these robust dishes, making every bite a hearty high-five to your taste buds!<br/><br/></p>
            </div>

            <div className="stout">
                <p className="title-stout">STOUT</p>
                <p className="vibe-stout">The Vibe: Snowflakes outside, a plush armchair, and the comforting aroma of home-cooked food.</p>
                <p className="content-stout">Stout, the deep and velvety poet of beers, is perfect for those introspective moments. Pair it with a slow-cooked lamb shank, a rich and gooey chocolate brownie, or a plate of blue cheese and figs. Stout's roasted notes elevate these dishes, making every bite a comforting caress.<br/><br/></p>
            </div>

            <div className="ipa">
                <p className="title-ipa">INDIA PALE ALE (IPA)</p>
                <p className="vibe-ipa">The Vibe: A bustling street festival, vibrant colors, and the thrill of discovery.</p>
                <p className="content-ipa">IPA, the audacious adventurer, is all about the hops and the heat. Dive into a spicy Mexican taco, savor a tangy Thai curry, or bite into a fiery jerk chicken. IPA's boldness stands tall, turning every meal into a carnival of flavors!<br/><br/></p>
            </div>

            <div className="pilsner">
                <p className="title-pilsner">PILSNER</p>
                <p className="vibe-pilsner">The Vibe: A rooftop soiree, twinkling city lights, and the clink of crystal glasses.</p>
                <p className="content-pilsner">Pilsner, the epitome of elegance, is all about the finer things in life. Indulge in a plate of sushi, savor a truffle-infused pasta, or enjoy a delicate salmon tartare. Pilsner's grace complements these dishes, making every bite a taste of luxury.<br/><br/></p>
            </div>

            <div className="wheat-beer">
                <p className="title-wheat-beer">WHEAT BEER</p>
                <p className="vibe-wheat-beer">The Vibe: Lazy Sunday mornings, the rustle of newspapers, and the joy of a brunch spread.</p>
                <p className="content-wheat-beer">Wheat Beer, the cheerful brunch buddy, is all about lightness and zest. Delight in a fluffy Belgian waffle, a citrusy fruit salad, or a creamy quiche. Wheat Beer's playful bubbles turn every brunch into a sun-kissed celebration!<br/><br/></p>
            </div>

            <p className="closing">From sunlit beaches to cozy winter cabins, beer is the universal companion that celebrates every flavor, every moment, and every memory. Each brew, with its distinct personality, paints a vivid picture, turning meals into stories and bites into adventures. So, pop open a bottle, pour yourself a pint, and let the culinary journey begin. To the magic of malt, the beauty of barley, and the wonder of wheat! Cheers to the world on our plates and the brews in our glasses! 🍺🍴🎊</p>
        </div>
    </div>
  );
}
