// src/app/spirit/spirit-overview/spirit-overview.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-spirit-overview',
  templateUrl: './spirit-overview.component.html',
  styleUrls: ['./spirit-overview.component.css']
})
export class SpiritOverviewComponent {

}

<div class="container">
    <p class="title">The Spirited Tale of Distilled Delights:</p>
    <p class="content">In a realm where traditions and tastes intertwined, a question arose: "How might we craft a drink that captures the essence of nature and time?" Thus, the art of distillation was unveiled, giving birth to spirits that would enchant generations.<br>
        <br>
        This wasn't just a mere drink; it was alchemy in a bottle. Grains and fruits, which once flourished under the sun's embrace, underwent a transformation. They whispered, "Why remain simple when we can be sublime?" And so, they embarked on a journey of fermentation and distillation, aspiring to become the soul of the finest spirits.<br>
        <br>
        But this transformation was a collective endeavor. Water, pure and pristine, played its part, diluting and refining. Then came the barrels, crafted from the finest oaks, which cradled these spirits, allowing them to mature, mellow, and gather character with each passing season. And in this process, the spirits absorbed the tales of time, becoming richer and more complex.<br>
        <br>
        From one corner of the world to another, these spirits traveled, weaving stories, sparking conversations, and igniting passions. And so unfolds the saga of spirits, the distilled wonders that have, over centuries, captured hearts and souls with their depth and elegance.
    </p>
</div>

// src/components/spirit/SpiritOverview.tsx
import './SpiritOverview.css';

export default function SpiritOverview() {
  return (
    <div className="spirit-overview-container">
        <p className="spirit-overview-title">The Spirited Tale of Distilled Delights:</p>
        <p className="spirit-overview-content">In a realm where traditions and tastes intertwined, a question arose: "How might we craft a drink that captures the essence of nature and time?" Thus, the art of distillation was unveiled, giving birth to spirits that would enchant generations.<br/>
            <br/>
            This wasn't just a mere drink; it was alchemy in a bottle. Grains and fruits, which once flourished under the sun's embrace, underwent a transformation. They whispered, "Why remain simple when we can be sublime?" And so, they embarked on a journey of fermentation and distillation, aspiring to become the soul of the finest spirits.<br/>
            <br/>
            But this transformation was a collective endeavor. Water, pure and pristine, played its part, diluting and refining. Then came the barrels, crafted from the finest oaks, which cradled these spirits, allowing them to mature, mellow, and gather character with each passing season. And in this process, the spirits absorbed the tales of time, becoming richer and more complex.<br/>
            <br/>
            From one corner of the world to another, these spirits traveled, weaving stories, sparking conversations, and igniting passions. And so unfolds the saga of spirits, the distilled wonders that have, over centuries, captured hearts and souls with their depth and elegance.
        </p>
    </div>
  );
}
