// src/components/rice-alcohol/RiceAlcoholHistory.tsx
import './RiceAlcoholHistory.css';

export default function RiceAlcoholHistory() {
  return (
    <div className="rice-alcohol-history-container">
        <p className="rice-alcohol-history-title">
            A Grainy Tale: The Odyssey of Rice Spirits</p>
        <div className="rice-alcohol-history-content">
            <p className="p1">
                Our story begins in the verdant rice paddies of ancient China, around 7,000 BC. As the legend goes, some soaked rice grains were left forgotten, only to ferment and transform into a sweet, aromatic liquid. This was the birth of Mijiu, China's cherished rice wine. The Chinese revered Mijiu, believing it to be a gift from the heavens. It became an integral part of rituals, ceremonies, and celebrations. The art of brewing Mijiu was considered sacred, passed down through generations, with each brewer adding their unique touch.
            <br/><br/></p>
            <p className="p2">
                As the winds of trade and exploration blew, the allure of rice-based alcohols wafted to neighboring regions. In ancient Japan, around 300 BC, the brewing of Sake began. Sake, often referred to as 'rice wine', is a misnomer, for its brewing process is more akin to beer. The Japanese elevated Sake brewing to an art form, with Shinto priests and shrine maidens playing pivotal roles. Sake became synonymous with purity and divinity, consumed to forge bonds with the gods and among men.
            <br/><br/></p>
            <p className="p3">
                Journeying southwards, we reach the vibrant lands of Southeast Asia. In Vietnam, the tradition of brewing Rượu cần, a communal rice spirit, took root. Villagers would gather around large jars with long bamboo straws, sipping and celebrating life's moments. Over in the Philippines, Tapuy, a traditional rice wine, was brewed with age-old techniques, often accompanied by rituals and dances to honor ancestral spirits and ensure a bountiful harvest.
            <br/><br/></p>
            <p className="p4">
                The tapestry of rice alcohols is incomplete without mentioning Korea's Soju and Laos' Lao-Lao. Soju, with its potent kick, has origins dating back to the 13th century during the Goryeo dynasty. Initially a drink of the royals, it soon found favor among the masses. Lao-Lao, on the other hand, with its earthy tones, became a symbol of Laotian hospitality, often shared with guests and travelers, forging bonds of friendship.
            <br/><br/></p>
            <p className="p5">
                Today, rice-based alcohols stand as a testament to the rich tapestry of cultures and traditions. From the bustling streets of Tokyo, where Sake is paired with delicate sushi, to the vibrant night markets of Seoul, where Soju shots echo laughter and camaraderie, these spirits continue to evolve. Modern mixologists are weaving them into contemporary cocktails, while microbreweries experiment with flavors and techniques. The journey of rice spirits, from ancient fields to modern glasses, is a tale of innovation, tradition, and an undying love for the grain that binds cultures together.
            <br/><br/></p>
        </div>
    </div>
  );
}

// src/app/rice-alcohol/rice-alcohol-history/rice-alcohol-history.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-history',
  templateUrl: './rice-alcohol-history.component.html',
  styleUrls: ['./rice-alcohol-history.component.css']
})
export class RiceAlcoholHistoryComponent {

}

<div class="container">
    <p class="title">
        A Grainy Tale: The Odyssey of Rice Spirits</p>
    <div class="content">
        <p class="p1">
            Our story begins in the verdant rice paddies of ancient China, around 7,000 BC. As the legend goes, some soaked rice grains were left forgotten, only to ferment and transform into a sweet, aromatic liquid. This was the birth of Mijiu, China's cherished rice wine. The Chinese revered Mijiu, believing it to be a gift from the heavens. It became an integral part of rituals, ceremonies, and celebrations. The art of brewing Mijiu was considered sacred, passed down through generations, with each brewer adding their unique touch.
        <br><br></p>
        <p class="p2">
            As the winds of trade and exploration blew, the allure of rice-based alcohols wafted to neighboring regions. In ancient Japan, around 300 BC, the brewing of Sake began. Sake, often referred to as 'rice wine', is a misnomer, for its brewing process is more akin to beer. The Japanese elevated Sake brewing to an art form, with Shinto priests and shrine maidens playing pivotal roles. Sake became synonymous with purity and divinity, consumed to forge bonds with the gods and among men.
        <br><br></p>
        <p class="p3">
            Journeying southwards, we reach the vibrant lands of Southeast Asia. In Vietnam, the tradition of brewing Rượu cần, a communal rice spirit, took root. Villagers would gather around large jars with long bamboo straws, sipping and celebrating life's moments. Over in the Philippines, Tapuy, a traditional rice wine, was brewed with age-old techniques, often accompanied by rituals and dances to honor ancestral spirits and ensure a bountiful harvest.
        <br><br></p>
        <p class="p4">
            The tapestry of rice alcohols is incomplete without mentioning Korea's Soju and Laos' Lao-Lao. Soju, with its potent kick, has origins dating back to the 13th century during the Goryeo dynasty. Initially a drink of the royals, it soon found favor among the masses. Lao-Lao, on the other hand, with its earthy tones, became a symbol of Laotian hospitality, often shared with guests and travelers, forging bonds of friendship.
        <br><br></p>
        <p class="p5">
            Today, rice-based alcohols stand as a testament to the rich tapestry of cultures and traditions. From the bustling streets of Tokyo, where Sake is paired with delicate sushi, to the vibrant night markets of Seoul, where Soju shots echo laughter and camaraderie, these spirits continue to evolve. Modern mixologists are weaving them into contemporary cocktails, while microbreweries experiment with flavors and techniques. The journey of rice spirits, from ancient fields to modern glasses, is a tale of innovation, tradition, and an undying love for the grain that binds cultures together.
        <br><br></p>
    </div>
</div>
