// src/components/spirit/SpiritTypes.tsx
import './SpiritTypes.css';

export default function SpiritTypes() {
  return (
    <div className="spirit-types-container">
        <p className="spirit-types-title">The Liquor Library:</p>
        <div className="spirit-types-content">
            <p className="title-whiskey">WHISKEY</p>
            <p className="content-whiskey">Whiskey, originating from the Gaelic word 'uisge beatha' meaning 'water of life', is a testament to the art of distillation. With flavors ranging from the smoky, peaty notes of Islay Scotch to the vanilla and oak undertones of Kentucky Bourbon, each sip is a journey through its aging process. The unique terroir of its origin, be it the highlands of Scotland or the green pastures of Ireland, imparts distinct flavors, making every bottle a narrative of its homeland.</p><br/>

            <p className="title-vodka">VODKA</p>
            <p className="content-vodka">Vodka, often perceived as flavorless, is a canvas of subtle tastes. Its origins in Russia and Poland introduced the world to a spirit that celebrates the essence of its base ingredient, be it grain, potato, or even grapes. The meticulous distillation process reveals hints of pepper, cream, and even fruit undertones, especially in artisanal batches. It's a spirit that whispers its nuances, challenging the palate to discern its secrets.</p><br/>

            <p className="title-rum">RUM</p>
            <p className="content-rum">Rum, the Caribbean's liquid sunshine, is a dance of flavors on the palate. From the light, grassy notes of agricole rums to the caramel and chocolate hints in aged variants, it's a tropical fiesta. The aging process, often in charred barrels, imparts flavors of vanilla, banana, and even tobacco, making every variant of rum a unique tasting adventure.</p><br/>

            <p className="title-tequila">TEQUILA & MEZCAL</p>
            <p className="content-tequila">Tequila and Mezcal, distilled from the agave plant, are the heartbeats of Mexico. While Tequila, made from blue agave, offers fresh and crisp notes of citrus, Mezcal, made from various agave types, introduces a smoky depth. The roasting of the agave hearts for Mezcal imparts flavors ranging from earthy to fruity, with hints of charred wood and even chocolate.</p><br/>

            <p className="title-gin">GIN</p>
            <p className="content-gin">Gin, distilled with an orchestra of botanicals, is a garden in a glass. Juniper berries provide the signature pine note, but the addition of herbs like coriander, citrus peels, and even exotic spices like cardamom, create a complex flavor profile. Modern gins often experiment with local botanicals, introducing flavors like lavender, cucumber, or even rose, making it a constantly evolving spirit.</p><br/>

            <p className="title-brandy">BRANDY</p>
            <p className="content-brandy">Brandy, the distilled essence of wine, is a symphony of flavors. The aging process in oak barrels introduces notes of dried fruit, nuts, and even hints of spice. Depending on its origin, be it the vineyards of Cognac or the rustic cellars of Spain, brandies can offer flavors ranging from apricot to almond, with a smooth, velvety finish that lingers.</p><br/>

            <p className="closing">From the rugged coastlines of Scotland to the sun-drenched agave fields of Mexico, every spirit is a reflection of its heritage, a blend of tradition and innovation. Each bottle tells a story, not just of its making, but of the land, the climate, and the generations of craftsmen behind it. Here's to the world in a glass! 🥃</p>
        </div>
    </div>
  );
}

// src/app/spirit/spirit-types/spirit-types.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-spirit-types',
  templateUrl: './spirit-types.component.html',
  styleUrls: ['./spirit-types.component.css']
})
export class SpiritTypesComponent {

}

<div class="container">
    <p class="title">The Liquor Library:</p>
    <div class="content">
        <p class="title-whiskey">WHISKEY</p>
        <p class="content-whiskey">Whiskey, originating from the Gaelic word 'uisge beatha' meaning 'water of life', is a testament to the art of distillation. With flavors ranging from the smoky, peaty notes of Islay Scotch to the vanilla and oak undertones of Kentucky Bourbon, each sip is a journey through its aging process. The unique terroir of its origin, be it the highlands of Scotland or the green pastures of Ireland, imparts distinct flavors, making every bottle a narrative of its homeland.</p><br>

        <p class="title-vodka">VODKA</p>
        <p class="content-vodka">Vodka, often perceived as flavorless, is a canvas of subtle tastes. Its origins in Russia and Poland introduced the world to a spirit that celebrates the essence of its base ingredient, be it grain, potato, or even grapes. The meticulous distillation process reveals hints of pepper, cream, and even fruit undertones, especially in artisanal batches. It's a spirit that whispers its nuances, challenging the palate to discern its secrets.</p><br>

        <p class="title-rum">RUM</p>
        <p class="content-rum">Rum, the Caribbean's liquid sunshine, is a dance of flavors on the palate. From the light, grassy notes of agricole rums to the caramel and chocolate hints in aged variants, it's a tropical fiesta. The aging process, often in charred barrels, imparts flavors of vanilla, banana, and even tobacco, making every variant of rum a unique tasting adventure.</p><br>

        <p class="title-tequila">TEQUILA & MEZCAL</p>
        <p class="content-tequila">Tequila and Mezcal, distilled from the agave plant, are the heartbeats of Mexico. While Tequila, made from blue agave, offers fresh and crisp notes of citrus, Mezcal, made from various agave types, introduces a smoky depth. The roasting of the agave hearts for Mezcal imparts flavors ranging from earthy to fruity, with hints of charred wood and even chocolate.</p><br>

        <p class="title-gin">GIN</p>
        <p class="content-gin">Gin, distilled with an orchestra of botanicals, is a garden in a glass. Juniper berries provide the signature pine note, but the addition of herbs like coriander, citrus peels, and even exotic spices like cardamom, create a complex flavor profile. Modern gins often experiment with local botanicals, introducing flavors like lavender, cucumber, or even rose, making it a constantly evolving spirit.</p><br>

        <p class="title-brandy">BRANDY</p>
        <p class="content-brandy">Brandy, the distilled essence of wine, is a symphony of flavors. The aging process in oak barrels introduces notes of dried fruit, nuts, and even hints of spice. Depending on its origin, be it the vineyards of Cognac or the rustic cellars of Spain, brandies can offer flavors ranging from apricot to almond, with a smooth, velvety finish that lingers.</p><br>

        <p class="closing">From the rugged coastlines of Scotland to the sun-drenched agave fields of Mexico, every spirit is a reflection of its heritage, a blend of tradition and innovation. Each bottle tells a story, not just of its making, but of the land, the climate, and the generations of craftsmen behind it. Here's to the world in a glass! 🥃</p>
    </div>
</div>
