// src/app/wine/wine-process/wine-process.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-process',
  templateUrl: './wine-process.component.html',
  styleUrls: ['./wine-process.component.css']
})
export class WineProcessComponent {

}

<div class="container">
    <p class="title">The Mystical Craft of Vinification:</p>
    <div class="content">
        <p class="title-red">RED WINE</p>
        <p class="content-red">The journey of red wine begins with the meticulous selection of dark-skinned grapes. These grapes, nurtured by the sun and soil, are the heart of red wine. Once picked, they are de-stemmed and crushed, releasing their vibrant juice. This juice is then left in contact with the grape skins and seeds during fermentation. This crucial step imparts the deep red hue and tannic character to the wine, giving it its signature robust flavor.
            <br><br>
            After fermentation, the wine undergoes a separation process where it is freed from the solid residues. It is then transferred to oak barrels or stainless steel tanks for aging. As the months and years pass, the wine undergoes a transformation, maturing and developing its intricate flavors and aromas. The result is a drink that not only tantalizes the taste buds but also tells a story of the land from which it came.</p><br>

        <p class="title-white">WHITE WINE</p>
        <p class="content-white">White wine's journey is one of elegance and precision. It starts with the harvesting of green or yellow-skinned grapes. These grapes, often hand-picked, are treated with care to preserve their delicate flavors. Upon reaching the winery, they are immediately crushed, and the skins are separated from the juice. This ensures that the wine remains clear, capturing the essence of the grape's natural flavors.
            <br><br>
            The clear juice then undergoes fermentation, a transformative process where sugars become alcohol, giving the wine its character. Once fermentation is complete, the wine is clarified, ensuring purity and brilliance. Depending on the desired profile, the wine may be aged in barrels or tanks, each imparting distinct characteristics. The final white wine is a harmonious blend of freshness, acidity, and fruitiness, making it a favorite for many.</p><br>

        <p class="title-rose">ROSÉ</p>
        <p class="content-rose">Rosé wine is the embodiment of summer in a bottle. Its production is a delicate balance between the methods used for red and white wines. Dark-skinned grapes are chosen, and upon crushing, the juice is allowed to mingle with the skins. However, this contact is fleeting, just enough to impart the wine's iconic pink shade.
            <br><br>
            After this brief maceration, the juice is drained off and fermented without the skins. This fermentation is often done in cool temperatures to retain the wine's fruity and floral notes. Aging for rosé is typically shorter, emphasizing its youthful and vibrant character. The final rosé wine is a delightful blend of red fruit flavors with a crisp finish, making it a versatile choice for various occasions.</p><br>

        <p class="title-sparkling">SPARKLING WINE</p>
        <p class="content-sparkling">Sparkling wine is a celebration in every sip. Its production is a testament to the winemaker's skill and patience. The base wine is first crafted, often using specific grape varieties known for their acidity and structure. This base wine then becomes the canvas for the sparkling wine's effervescence. A mixture of sugar and yeast, known as the 'liqueur de tirage', is added, initiating the second fermentation within the sealed bottle.
            <br><br>
            As the yeast consumes the sugar, it produces carbon dioxide, creating the wine's signature bubbles. Once this fermentation is complete, the wine undergoes a process called 'riddling', where the dead yeast cells are consolidated. These are then removed, and the wine is corked, sealing in the effervescence. The result is a lively and bubbly drink, perfect for celebrations and special moments.</p><br>

        <p class="title-pilsner">DESSERT WINE</p>
        <p class="content-pilsner">Dessert wines are nature's sweet gift to wine lovers. These wines start their journey with grapes that are left on the vine longer than usual. This extended ripening period allows the grapes to develop intense sweetness, often enhanced by natural processes like noble rot or freezing. Once harvested, these sugar-rich grapes are pressed, producing a luscious juice.
            <br><br>
            During fermentation, the high sugar content poses a challenge, often halting the process and leaving behind a significant amount of residual sugar. This gives dessert wines their characteristic sweetness. Aging plays a crucial role in refining these wines, often in oak barrels, adding depth and complexity. The final dessert wine is a symphony of sweetness, balanced by acidity, and packed with flavors of dried fruits, honey, and spices.</p><br>

        <p class="title-fortified">FORTIFIED WINE</p>
        <p class="content-fortified">Fortified wines are a harmonious blend of wine and spirit. Their journey begins similarly to other wines, with the fermentation of grape juice. However, the twist comes mid-way. Before fermentation completes, a high-proof spirit, usually grape brandy, is added. This addition not only halts fermentation but also elevates the wine's alcohol content, giving it a robust character.
            <br><br>
            The type of fortified wine, be it Port, Sherry, or Madeira, dictates its subsequent aging process. Some are aged oxidatively, exposed to air, while others are aged in a sealed environment. These aging methods impart unique flavors and profiles to the wines. The end product is a potent and flavorful wine, with layers of complexity, best enjoyed in small sips.</p><br>

        <p class="closing">The art of wine-making is a dance of nature and nurture, a blend of tradition and innovation. From the sun-kissed vineyards to the aged oak barrels, every step is a testament to passion and patience. As we raise our glasses, let's toast to the vintners, the grapes, and the age-old rituals that gift us these bottled wonders. Cheers to the world of wine and its enchanting elixirs! 🍷🍇🥂</p>
    </div>
</div>

// src/components/wine/WineProcess.tsx
import './WineProcess.css';

export default function WineProcess() {
  return (
    <div className="wine-process-container">
        <p className="wine-process-title">The Mystical Craft of Vinification:</p>
        <div className="wine-process-content">
            <p className="title-red">RED WINE</p>
            <p className="content-red">The journey of red wine begins with the meticulous selection of dark-skinned grapes. These grapes, nurtured by the sun and soil, are the heart of red wine. Once picked, they are de-stemmed and crushed, releasing their vibrant juice. This juice is then left in contact with the grape skins and seeds during fermentation. This crucial step imparts the deep red hue and tannic character to the wine, giving it its signature robust flavor.
                <br/><br/>
                After fermentation, the wine undergoes a separation process where it is freed from the solid residues. It is then transferred to oak barrels or stainless steel tanks for aging. As the months and years pass, the wine undergoes a transformation, maturing and developing its intricate flavors and aromas. The result is a drink that not only tantalizes the taste buds but also tells a story of the land from which it came.</p><br/>

            <p className="title-white">WHITE WINE</p>
            <p className="content-white">White wine's journey is one of elegance and precision. It starts with the harvesting of green or yellow-skinned grapes. These grapes, often hand-picked, are treated with care to preserve their delicate flavors. Upon reaching the winery, they are immediately crushed, and the skins are separated from the juice. This ensures that the wine remains clear, capturing the essence of the grape's natural flavors.
                <br/><br/>
                The clear juice then undergoes fermentation, a transformative process where sugars become alcohol, giving the wine its character. Once fermentation is complete, the wine is clarified, ensuring purity and brilliance. Depending on the desired profile, the wine may be aged in barrels or tanks, each imparting distinct characteristics. The final white wine is a harmonious blend of freshness, acidity, and fruitiness, making it a favorite for many.</p><br/>

            <p className="title-rose">ROSÉ</p>
            <p className="content-rose">Rosé wine is the embodiment of summer in a bottle. Its production is a delicate balance between the methods used for red and white wines. Dark-skinned grapes are chosen, and upon crushing, the juice is allowed to mingle with the skins. However, this contact is fleeting, just enough to impart the wine's iconic pink shade.
                <br/><br/>
                After this brief maceration, the juice is drained off and fermented without the skins. This fermentation is often done in cool temperatures to retain the wine's fruity and floral notes. Aging for rosé is typically shorter, emphasizing its youthful and vibrant character. The final rosé wine is a delightful blend of red fruit flavors with a crisp finish, making it a versatile choice for various occasions.</p><br/>

            <p className="title-sparkling">SPARKLING WINE</p>
            <p className="content-sparkling">Sparkling wine is a celebration in every sip. Its production is a testament to the winemaker's skill and patience. The base wine is first crafted, often using specific grape varieties known for their acidity and structure. This base wine then becomes the canvas for the sparkling wine's effervescence. A mixture of sugar and yeast, known as the 'liqueur de tirage', is added, initiating the second fermentation within the sealed bottle.
                <br/><br/>
                As the yeast consumes the sugar, it produces carbon dioxide, creating the wine's signature bubbles. Once this fermentation is complete, the wine undergoes a process called 'riddling', where the dead yeast cells are consolidated. These are then removed, and the wine is corked, sealing in the effervescence. The result is a lively and bubbly drink, perfect for celebrations and special moments.</p><br/>

            <p className="title-pilsner">DESSERT WINE</p>
            <p className="content-pilsner">Dessert wines are nature's sweet gift to wine lovers. These wines start their journey with grapes that are left on the vine longer than usual. This extended ripening period allows the grapes to develop intense sweetness, often enhanced by natural processes like noble rot or freezing. Once harvested, these sugar-rich grapes are pressed, producing a luscious juice.
                <br/><br/>
                During fermentation, the high sugar content poses a challenge, often halting the process and leaving behind a significant amount of residual sugar. This gives dessert wines their characteristic sweetness. Aging plays a crucial role in refining these wines, often in oak barrels, adding depth and complexity. The final dessert wine is a symphony of sweetness, balanced by acidity, and packed with flavors of dried fruits, honey, and spices.</p><br/>

            <p className="title-fortified">FORTIFIED WINE</p>
            <p className="content-fortified">Fortified wines are a harmonious blend of wine and spirit. Their journey begins similarly to other wines, with the fermentation of grape juice. However, the twist comes mid-way. Before fermentation completes, a high-proof spirit, usually grape brandy, is added. This addition not only halts fermentation but also elevates the wine's alcohol content, giving it a robust character.
                <br/><br/>
                The type of fortified wine, be it Port, Sherry, or Madeira, dictates its subsequent aging process. Some are aged oxidatively, exposed to air, while others are aged in a sealed environment. These aging methods impart unique flavors and profiles to the wines. The end product is a potent and flavorful wine, with layers of complexity, best enjoyed in small sips.</p><br/>

            <p className="closing">The art of wine-making is a dance of nature and nurture, a blend of tradition and innovation. From the sun-kissed vineyards to the aged oak barrels, every step is a testament to passion and patience. As we raise our glasses, let's toast to the vintners, the grapes, and the age-old rituals that gift us these bottled wonders. Cheers to the world of wine and its enchanting elixirs! 🍷🍇🥂</p>
        </div>
    </div>
  );
}
