// src/app/wine/wine-brands/wine-brands.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-brands',
  templateUrl: './wine-brands.component.html',
  styleUrls: ['./wine-brands.component.css']
})
export class WineBrandsComponent {

}

<div class="container">
    <p class="title">World's Wine Titans (The Top Producers):</p>
    <div class="content">

        <p class="title-gallo">E. & J. GALLO WINERY</p>
        <p class="content-gallo">Founded in 1933 by brothers Ernest and Julio Gallo in Modesto, California, E. & J. Gallo Winery has grown to become the largest family-owned winery in the world. With over 80 years of winemaking expertise, they own vineyards in some of the most esteemed regions, producing everything from affordable table wines to premium labels. Their commitment to sustainability and innovation has set them apart in the industry.</p><br>

        <p class="title-constellation">CONSTELLATION BRANDS</p>
        <p class="content-constellation">Established in 1945, Constellation Brands began as a small wine company in upstate New York. Today, it's a global behemoth, owning more than 100 brands across wine, beer, and spirits. Their wine portfolio includes esteemed brands like Robert Mondavi, Clos du Bois, and Kim Crawford. Their success lies in their ability to adapt to market trends while maintaining quality.</p><br>

        <p class="title-winegroup">THE WINE GROUP</p>
        <p class="content-winegroup">The Wine Group, founded in 1981, might be younger than its counterparts, but its impact is undeniable. As the world's third-largest wine producer by volume, it's behind everyday favorites like Franzia box wines and more premium offerings like Benziger Family Winery. Their ethos revolves around making quality wine accessible to all.</p><br>

        <p class="title-treasury">TREASURY WINE ESTATES</p>
        <p class="content-treasury">Originating from the merger of two Australian wine companies in 2011, Treasury Wine Estates has a rich heritage. With vineyards in Australia, New Zealand, and the U.S., they produce some of the most recognized wines globally. Brands like Penfolds, known for the Grange, and Beringer, the oldest continuously operating winery in Napa Valley, are part of their illustrious portfolio.</p><br>

        <p class="title-castel">CASTEL GROUP</p>
        <p class="content-castel">The Castel Group, founded in 1949 by nine siblings, is a family-run enterprise that has become a European wine powerhouse. Based in Bordeaux, France, they own vineyards across France, from Bordeaux to the Rhône Valley. They're also pioneers in African viticulture, with vineyards in Morocco and Tunisia. Their approach combines respect for tradition with a spirit of innovation.</p><br>

        <p class="closing">From humble beginnings to global dominance, these wine producers have etched their names in the annals of wine history. Their stories are a testament to the power of passion, vision, and resilience. As we savor each sip, we're not just tasting wine; we're experiencing a piece of a grand legacy. Here's to the maestros of the vineyard! 🍷🌏🍇</p>
    </div>
</div>

// src/components/wine/WineBrands.tsx
import './WineBrands.css';

export default function WineBrands() {
  return (
    <div className="wine-brands-container">
        <p className="wine-brands-title">World's Wine Titans (The Top Producers):</p>
        <div className="wine-brands-content">

            <p className="title-gallo">E. & J. GALLO WINERY</p>
            <p className="content-gallo">Founded in 1933 by brothers Ernest and Julio Gallo in Modesto, California, E. & J. Gallo Winery has grown to become the largest family-owned winery in the world. With over 80 years of winemaking expertise, they own vineyards in some of the most esteemed regions, producing everything from affordable table wines to premium labels. Their commitment to sustainability and innovation has set them apart in the industry.</p><br/>

            <p className="title-constellation">CONSTELLATION BRANDS</p>
            <p className="content-constellation">Established in 1945, Constellation Brands began as a small wine company in upstate New York. Today, it's a global behemoth, owning more than 100 brands across wine, beer, and spirits. Their wine portfolio includes esteemed brands like Robert Mondavi, Clos du Bois, and Kim Crawford. Their success lies in their ability to adapt to market trends while maintaining quality.</p><br/>

            <p className="title-winegroup">THE WINE GROUP</p>
            <p className="content-winegroup">The Wine Group, founded in 1981, might be younger than its counterparts, but its impact is undeniable. As the world's third-largest wine producer by volume, it's behind everyday favorites like Franzia box wines and more premium offerings like Benziger Family Winery. Their ethos revolves around making quality wine accessible to all.</p><br/>

            <p className="title-treasury">TREASURY WINE ESTATES</p>
            <p className="content-treasury">Originating from the merger of two Australian wine companies in 2011, Treasury Wine Estates has a rich heritage. With vineyards in Australia, New Zealand, and the U.S., they produce some of the most recognized wines globally. Brands like Penfolds, known for the Grange, and Beringer, the oldest continuously operating winery in Napa Valley, are part of their illustrious portfolio.</p><br/>

            <p className="title-castel">CASTEL GROUP</p>
            <p className="content-castel">The Castel Group, founded in 1949 by nine siblings, is a family-run enterprise that has become a European wine powerhouse. Based in Bordeaux, France, they own vineyards across France, from Bordeaux to the Rhône Valley. They're also pioneers in African viticulture, with vineyards in Morocco and Tunisia. Their approach combines respect for tradition with a spirit of innovation.</p><br/>

            <p className="closing">From humble beginnings to global dominance, these wine producers have etched their names in the annals of wine history. Their stories are a testament to the power of passion, vision, and resilience. As we savor each sip, we're not just tasting wine; we're experiencing a piece of a grand legacy. Here's to the maestros of the vineyard! 🍷🌏🍇</p>
        </div>
    </div>
  );
}
