// src/app/wine/wine-overview/wine-overview.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-overview',
  templateUrl: './wine-overview.component.html',
  styleUrls: ['./wine-overview.component.css']
})
export class WineOverviewComponent {

}

<div class="container">
    <p class="title">The Grand Wine Odyssey:</p>
    <p class="content">In epochs past, when civilizations were just beginning to touch the arts and sciences, a serendipitous discovery was made: wine. This wasn't just a drink; it was a symbol of culture, prosperity, and the joys of life itself.<br>
        <br>
        The tale of wine is as old as time. Born in the ancient valleys of Mesopotamia and the fertile crescents of the Nile, wine became the drink of pharaohs and kings. Grapes, under the gentle caress of the sun and the nurturing embrace of the earth, matured with a promise of greatness. They whispered tales of seasons gone by and held within them the mysteries of the terroir.<br>
        <br>
        But the journey from grape to glass was one of artistry and patience. The vintners, with their age-old knowledge and ancestral techniques, played a pivotal role. They understood the dance of fermentation, the delicate balance of tannins, and the symphony of flavors that needed to be orchestrated. Each wine, whether the robust reds of Bordeaux or the crisp whites of the Loire Valley, told a story of its land, its climate, and its heritage.<br>
        <br>
        As empires rose and fell, wine flowed along trade routes, gracing the tables of the mighty and the humble alike. It inspired poets, fueled revolutions, and sealed pacts. Monasteries preserved its crafting techniques, while merchants spread its allure to new lands. From the Roman bacchanals to the sophisticated salons of Paris, wine has been both a muse and a companion.<br>
        <br>
        Today, as we swirl our glasses and savor the notes of berries, oak, and time, we partake in a tradition millennia old. And that, dear reader, is the odyssey of wine, a journey through history, nature, and the very essence of humanity.
    </p>
</div>

// src/components/wine/WineOverview.tsx
import './WineOverview.css';

export default function WineOverview() {
  return (
    <div className="wine-overview-container">
        <p className="wine-overview-title">The Grand Wine Odyssey:</p>
        <p className="wine-overview-content">In epochs past, when civilizations were just beginning to touch the arts and sciences, a serendipitous discovery was made: wine. This wasn't just a drink; it was a symbol of culture, prosperity, and the joys of life itself.<br/>
            <br/>
            The tale of wine is as old as time. Born in the ancient valleys of Mesopotamia and the fertile crescents of the Nile, wine became the drink of pharaohs and kings. Grapes, under the gentle caress of the sun and the nurturing embrace of the earth, matured with a promise of greatness. They whispered tales of seasons gone by and held within them the mysteries of the terroir.<br/>
            <br/>
            But the journey from grape to glass was one of artistry and patience. The vintners, with their age-old knowledge and ancestral techniques, played a pivotal role. They understood the dance of fermentation, the delicate balance of tannins, and the symphony of flavors that needed to be orchestrated. Each wine, whether the robust reds of Bordeaux or the crisp whites of the Loire Valley, told a story of its land, its climate, and its heritage.<br/>
            <br/>
            As empires rose and fell, wine flowed along trade routes, gracing the tables of the mighty and the humble alike. It inspired poets, fueled revolutions, and sealed pacts. Monasteries preserved its crafting techniques, while merchants spread its allure to new lands. From the Roman bacchanals to the sophisticated salons of Paris, wine has been both a muse and a companion.<br/>
            <br/>
            Today, as we swirl our glasses and savor the notes of berries, oak, and time, we partake in a tradition millennia old. And that, dear reader, is the odyssey of wine, a journey through history, nature, and the very essence of humanity.
        </p>
    </div>
  );
}
