// src/components/liqueur/LiqueurBrands.tsx
import './LiqueurBrands.css';

export default function LiqueurBrands() {
  return (
    <div className="liqueur-brands-container">
        <p className="liqueur-brands-title">Liqueur Legends: The Titans of Taste</p>
        <div className="liqueur-brands-content">

            <p className="title-diageo">DIAGEO</p>
            <p className="content-diageo">Based in the United Kingdom, Diageo stands tall as a global leader in the alcoholic beverages sector. As one of the world's largest producers of spirits, their portfolio boasts iconic brands like Baileys, a creamy Irish delight; Cîroc, a premium vodka; and Captain Morgan, the spiced rum that has sailed into hearts worldwide. With a presence in over 180 countries, Diageo is a testament to British excellence in spirit production.</p><br/>

            <p className="title-pernod-ricard">PERNOD RICARD</p>
            <p className="content-pernod-ricard">Hailing from France, Pernod Ricard is a name that resonates with luxury and tradition in the world of wines and spirits. Holding the title of the world's second-largest producer, their collection features brands like Malibu, a coconut-flavored rum; Kahlúa, the coffee liqueur loved by many; and Beefeater, a gin that captures the essence of London. Their French roots combined with a global presence make them a force to reckon with in the industry.</p><br/>

            <p className="title-remy-cointreau">RÉMY COINTREAU</p>
            <p className="content-remy-cointreau">Another gem from France, Rémy Cointreau is synonymous with luxury and refinement. With a history that spans centuries, they are the proud producers of Cointreau, the famous orange liqueur that has added zest to cocktails worldwide. Their commitment to quality and innovation has cemented their position as one of the premium spirit producers on the globe.</p><br/>

            <p className="title-campari-group">CAMPARI GROUP</p>
            <p className="content-campari-group">Italy, a country known for its rich culinary heritage, is home to the Campari Group. Renowned for their bitter aperitifs, they have a diverse range of liqueurs that cater to varied palates. Brands like Aperol, with its unique orange hue and bittersweet taste, and Campari, a ruby-red concoction, are just a few of the treasures in their arsenal. Their Italian flair combined with a global vision makes them a favorite among connoisseurs.</p><br/>

            <p className="title-lucas-bols">LUCAS BOLS</p>
            <p className="content-lucas-bols">The Netherlands, known for its picturesque canals and windmills, is also home to Lucas Bols, one of the world's oldest distilled spirits companies. With a legacy that dates back to the 16th century, they offer a wide range of liqueurs, including Bols Genever, a traditional Dutch spirit, and Galliano, a sweet herbal liqueur. Their rich history and dedication to craft make them a standout in the world of liqueurs.</p><br/>

            <p className="closing">From the heart of Europe to the global stage, these producers have crafted elixirs that have stood the test of time. Each bottle they produce is a blend of tradition, innovation, and passion. As you savor their creations, remember the legacy and craftsmanship that goes into every drop. Here's to the maestros of the liqueur world! 🍸🌍🥂</p>
        </div>
    </div>
  );
}

// src/app/liqueur/liqueur-brands/liqueur-brands.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-liqueur-brands',
  templateUrl: './liqueur-brands.component.html',
  styleUrls: ['./liqueur-brands.component.css']
})
export class LiqueurBrandsComponent {

}

<div class="container">
    <p class="title">Liqueur Legends: The Titans of Taste</p>
    <div class="content">

        <p class="title-diageo">DIAGEO</p>
        <p class="content-diageo">Based in the United Kingdom, Diageo stands tall as a global leader in the alcoholic beverages sector. As one of the world's largest producers of spirits, their portfolio boasts iconic brands like Baileys, a creamy Irish delight; Cîroc, a premium vodka; and Captain Morgan, the spiced rum that has sailed into hearts worldwide. With a presence in over 180 countries, Diageo is a testament to British excellence in spirit production.</p><br>

        <p class="title-pernod-ricard">PERNOD RICARD</p>
        <p class="content-pernod-ricard">Hailing from France, Pernod Ricard is a name that resonates with luxury and tradition in the world of wines and spirits. Holding the title of the world's second-largest producer, their collection features brands like Malibu, a coconut-flavored rum; Kahlúa, the coffee liqueur loved by many; and Beefeater, a gin that captures the essence of London. Their French roots combined with a global presence make them a force to reckon with in the industry.</p><br>

        <p class="title-remy-cointreau">RÉMY COINTREAU</p>
        <p class="content-remy-cointreau">Another gem from France, Rémy Cointreau is synonymous with luxury and refinement. With a history that spans centuries, they are the proud producers of Cointreau, the famous orange liqueur that has added zest to cocktails worldwide. Their commitment to quality and innovation has cemented their position as one of the premium spirit producers on the globe.</p><br>

        <p class="title-campari-group">CAMPARI GROUP</p>
        <p class="content-campari-group">Italy, a country known for its rich culinary heritage, is home to the Campari Group. Renowned for their bitter aperitifs, they have a diverse range of liqueurs that cater to varied palates. Brands like Aperol, with its unique orange hue and bittersweet taste, and Campari, a ruby-red concoction, are just a few of the treasures in their arsenal. Their Italian flair combined with a global vision makes them a favorite among connoisseurs.</p><br>

        <p class="title-lucas-bols">LUCAS BOLS</p>
        <p class="content-lucas-bols">The Netherlands, known for its picturesque canals and windmills, is also home to Lucas Bols, one of the world's oldest distilled spirits companies. With a legacy that dates back to the 16th century, they offer a wide range of liqueurs, including Bols Genever, a traditional Dutch spirit, and Galliano, a sweet herbal liqueur. Their rich history and dedication to craft make them a standout in the world of liqueurs.</p><br>

        <p class="closing">From the heart of Europe to the global stage, these producers have crafted elixirs that have stood the test of time. Each bottle they produce is a blend of tradition, innovation, and passion. As you savor their creations, remember the legacy and craftsmanship that goes into every drop. Here's to the maestros of the liqueur world! 🍸🌍🥂</p>
    </div>
</div>
