// src/components/beer/BeerBrands.tsx
import './BeerBrands.css';

export default function BeerBrands() {
  return (
    <div className="beer-brands-container">
        <p className="beer-brands-title">A-List Amber Nectars (The Star Brands):</p>
        <div className="beer-brands-content">
            <p className="title-budweiser">BUDWEISER</p>
            <p className="content-budweiser">Hailing from the heartland of the United States, Budweiser is a brand that's become synonymous with American beer. Established in 1876 by Adolphus Busch and his friend Carl Conrad, this St. Louis-born brew was inspired by the Bohemian lager of the Czech Republic. With its distinct red label and the iconic Clydesdale horses, Budweiser has been a staple at American celebrations for generations. While it's often referred to as a light, crisp lager, the brewing process is anything but simple. It involves an exclusive beechwood aging process that imparts a smoothness to the final product.</p><br/>
                
            <p className="title-heineken">HEINEKEN</p>
            <p className="content-heineken">Founded in 1864 in Amsterdam, Heineken is a brand that's become a global ambassador for Dutch brewing. The signature green bottle and red star have graced bars in over 170 countries. What sets Heineken apart is its use of the 'A-Yeast', introduced by Dr. Elion in the late 19th century, which gives the beer its distinct balanced flavor. Fun fact: The Heineken Experience in Amsterdam offers a deep dive into its rich history and brewing process!</p><br/>
        
            <p className="title-corona">CORONA</p>
            <p className="content-corona">This sun-kissed Mexican lager has its roots in the city of Mexico but has found its way to beach parties worldwide. Founded in 1925, Corona is best known for its light, refreshing taste, often complemented with a wedge of lime. Its clear bottle, designed to show off its pale golden hue, is a nod to the sunny beaches of its homeland.</p><br/>

            <p className="title-guinness">GUINNESS</p>
            <p className="content-guinness">A sip of Guinness is like a journey through Irish history. Established in 1759 by Arthur Guinness, this Dublin-based stout is known for its creamy head and deep, roasted flavors. The beer owes its unique taste to the roasted unmalted barley used in its brewing. The Guinness Storehouse in Dublin remains one of Ireland's top tourist attractions, offering a panoramic view of the city along with a pint!</p><br/>

            <p className="title-stella-artois">Stella Artois</p>
            <p className="content-stella-artois">With origins dating back to 1366 in the city of Leuven, Belgium, Stella Artois is one of the world's oldest beer brands. The name "Stella" translates to "star" in Latin, a nod to the brand's commitment to stellar quality. Known for its rich golden color and crisp taste, Stella Artois often comes served in a chalice, ensuring the perfect head and aroma with each pour.</p><br/>

            <p className="title-carlsberg">CARLSBERG</p>
            <p className="content-carlsberg">TThis Danish delight was founded in 1847 by J.C. Jacobsen in Copenhagen. Named after Jacobsen's son, Carl, and the Danish word for hill ("bjerg"), Carlsberg is a testament to Scandinavian brewing excellence. The brand is also known for establishing the Carlsberg Laboratory, which played a pivotal role in developing a method to purify yeast, revolutionizing beer brewing globally.</p><br/>
                <br/>
            <p className="closing">In the vast universe of beers, these brands shine the brightest, each with its unique tale and taste. They're not just beverages; they're legacies poured into a glass. So, the next time you pop open one of these, remember the centuries of tradition and innovation that fizz within. Cheers to the legends of the lager! 🍻🌍🌟</p>
        </div>
    </div>
  );
}

// src/app/beer/beer-brands/beer-brands.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-beer-brands',
  templateUrl: './beer-brands.component.html',
  styleUrls: ['./beer-brands.component.css']
})
export class BeerBrandsComponent {

}

<div class="container">
    <p class="title">A-List Amber Nectars (The Star Brands):</p>
    <div class="content">
        <p class="title-budweiser">BUDWEISER</p>
        <p class="content-budweiser">Hailing from the heartland of the United States, Budweiser is a brand that's become synonymous with American beer. Established in 1876 by Adolphus Busch and his friend Carl Conrad, this St. Louis-born brew was inspired by the Bohemian lager of the Czech Republic. With its distinct red label and the iconic Clydesdale horses, Budweiser has been a staple at American celebrations for generations. While it's often referred to as a light, crisp lager, the brewing process is anything but simple. It involves an exclusive beechwood aging process that imparts a smoothness to the final product.</p><br>
            
        <p class="title-heineken">HEINEKEN</p>
        <p class="content-heineken">Founded in 1864 in Amsterdam, Heineken is a brand that's become a global ambassador for Dutch brewing. The signature green bottle and red star have graced bars in over 170 countries. What sets Heineken apart is its use of the 'A-Yeast', introduced by Dr. Elion in the late 19th century, which gives the beer its distinct balanced flavor. Fun fact: The Heineken Experience in Amsterdam offers a deep dive into its rich history and brewing process!</p><br>
    
        <p class="title-corona">CORONA</p>
        <p class="content-corona">This sun-kissed Mexican lager has its roots in the city of Mexico but has found its way to beach parties worldwide. Founded in 1925, Corona is best known for its light, refreshing taste, often complemented with a wedge of lime. Its clear bottle, designed to show off its pale golden hue, is a nod to the sunny beaches of its homeland.</p><br>

        <p class="title-guinness">GUINNESS</p>
        <p class="content-guinness">A sip of Guinness is like a journey through Irish history. Established in 1759 by Arthur Guinness, this Dublin-based stout is known for its creamy head and deep, roasted flavors. The beer owes its unique taste to the roasted unmalted barley used in its brewing. The Guinness Storehouse in Dublin remains one of Ireland's top tourist attractions, offering a panoramic view of the city along with a pint!</p><br>

        <p class="title-stella-artois">Stella Artois</p>
        <p class="content-stella-artois">With origins dating back to 1366 in the city of Leuven, Belgium, Stella Artois is one of the world's oldest beer brands. The name "Stella" translates to "star" in Latin, a nod to the brand's commitment to stellar quality. Known for its rich golden color and crisp taste, Stella Artois often comes served in a chalice, ensuring the perfect head and aroma with each pour.</p><br>

        <p class="title-carlsberg">CARLSBERG</p>
        <p class="content-carlsberg">TThis Danish delight was founded in 1847 by J.C. Jacobsen in Copenhagen. Named after Jacobsen's son, Carl, and the Danish word for hill ("bjerg"), Carlsberg is a testament to Scandinavian brewing excellence. The brand is also known for establishing the Carlsberg Laboratory, which played a pivotal role in developing a method to purify yeast, revolutionizing beer brewing globally.</p><br>
            <br>
        <p class="closing">In the vast universe of beers, these brands shine the brightest, each with its unique tale and taste. They're not just beverages; they're legacies poured into a glass. So, the next time you pop open one of these, remember the centuries of tradition and innovation that fizz within. Cheers to the legends of the lager! 🍻🌍🌟</p>
        </div>
    
</div>
