// src/components/rice-alcohol/RiceAlcoholFood.tsx
import './RiceAlcoholFood.css';

export default function RiceAlcoholFood() {
  return (
    <div className="rice-alcohol-food-container">
        <p className="rice-alcohol-food-title">Rice Spirits & Culinary Rhapsodies:</p>
        <div className="rice-alcohol-food-content">
            <div className="sake">
                <p className="title-sake">SAKE</p>
                <p className="vibe-sake">The Vibe: Tranquil Japanese gardens, cherry blossoms in full bloom, and the gentle strumming of a shamisen.</p>
                <p className="content-sake">Perfect Pairings: Sake, with its refined elegance, is the soulmate of sushi, where each grain of rice and slice of fish tells a story. Dive into the delicate flavors of sashimi, each piece a testament to the ocean's bounty. Or let the crispy allure of tempura, whether it's prawn or vegetables, dance on your palate. With every sip of Sake, these dishes come alive, echoing Japan's culinary artistry.<br/><br/></p>
            </div>

            <div className="soju">
                <p className="title-soju">SOJU</p>
                <p className="vibe-soju">The Vibe: Vibrant Seoul streets, neon lights, and the rhythmic beats of K-pop in the distance.</p>
                <p className="content-soju">Perfect Pairings: Soju's spirited charm is the heart of Korean feasts. Imagine the sizzle of Korean BBQ, each morsel grilled to perfection, or the fiery embrace of a kimchi stew, warming your soul. With Soju by your side, every bite is a celebration of Korea's rich flavors and zest for life.<br/><br/></p>
            </div>

            <div className="mijiu">
                <p className="title-mijiu">MIJIU</p>
                <p className="vibe-mijiu">The Vibe: Bustling Chinese markets, lanterns swaying, and the age-old wisdom of dynasties past.</p>
                <p className="content-mijiu">Perfect Pairings: Mijiu's subtle grace is the essence of Chinese delicacies. Dive into the world of dim sum, where each bite-sized delight is a culinary gem. Relish the crispy skin and tender meat of Peking duck, or let the sweet allure of mooncakes, symbolizing unity and prosperity, melt in your mouth. Mijiu elevates these dishes, weaving tales of China's rich gastronomic heritage.<br/><br/></p>
            </div>

            <div className="ruou-can">
                <p className="title-ruou-can">RƯỢU CẦN</p>
                <p className="vibe-ruou-can">The Vibe: Lush Vietnamese rice paddies, the gentle hum of the Mekong, and the aroma of fresh herbs in the air.</p>
                <p className="content-ruou-can">Perfect Pairings: Rượu cần's enchanting spirit is a journey through Vietnam's culinary wonders. Delight in the fresh crunch of Vietnamese spring rolls, a burst of flavors and textures. Dive into a bowl of pho, its aromatic broth a symphony of spices. Or savor the smoky flavors of grilled fish, a testament to Vietnam's rich coastal bounty. With Rượu cần, every dish is a mosaic of flavors, celebrating Vietnam's culinary tapestry.<br/><br/></p>
            </div>

            <div className="lao-lao">
                <p className="title-lao-lao">LAO-LAO</p>
                <p className="vibe-lao-lao">The Vibe: Tranquil Mekong sunsets, the distant chants from a monastery, and the warmth of Laotian smiles.</p>
                <p className="content-lao-lao">Perfect Pairings: Lao-Lao's earthy allure is the soul of Laotian feasts. Relish the flavors of Laap, a meat salad bursting with fresh herbs and spices. Let the comforting taste of sticky rice, a Laotian staple, complement your meal. Or explore the charred goodness of grilled vegetables, each bite a celebration of Laos' agrarian roots. Lao-Lao enhances these dishes, capturing the essence of Laotian hospitality and joy.<br/><br/></p>
            </div>

            <div className="tapuy">
                <p className="title-tapuy">TAPUY</p>
                <p className="vibe-tapuy">The Vibe: Vibrant Filipino fiestas, the harmonious tunes of a rondalla, and the shimmering blue of the Pacific.</p>
                <p className="content-tapuy">Perfect Pairings: Tapuy, with its festive spirit, is the heart of Filipino celebrations. Dive into the crispy, golden skin of lechon, a feast for the senses. Savor the savory embrace of adobo, a dance of soy, vinegar, and spices. And for a sweet finale, let the layers of halo-halo, with its colorful medley of ingredients, delight your palate. With Tapuy, every dish is a toast to the Philippines' culinary mosaic and islander spirit.<br/><br/></p>
            </div>
            
            <p className="closing">From the serene shores of Japan to the bustling streets of Seoul, and from the vast landscapes of China to the vibrant fiestas of the Philippines, rice-based alcohols are a journey through cultures, traditions, and flavors. Each drink, with its unique taste profile, complements and elevates the dishes of its homeland, creating a harmonious blend of tastes and memories. So, as you embark on this culinary voyage, let the spirits guide you, and may your palate discover new horizons. Cheers to the world on a plate and in a glass! 🥂🍽️🌏</p>
        </div>
    </div>
  );
}

// src/app/rice-alcohol/rice-alcohol-food/rice-alcohol-food.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-food',
  templateUrl: './rice-alcohol-food.component.html',
  styleUrls: ['./rice-alcohol-food.component.css']
})
export class RiceAlcoholFoodComponent {

}

<div class="container">
    <p class="title">Rice Spirits & Culinary Rhapsodies:</p>
    <div class="content">
        <div class="sake">
            <p class="title-sake">SAKE</p>
            <p class="vibe-sake">The Vibe: Tranquil Japanese gardens, cherry blossoms in full bloom, and the gentle strumming of a shamisen.</p>
            <p class="content-sake">Perfect Pairings: Sake, with its refined elegance, is the soulmate of sushi, where each grain of rice and slice of fish tells a story. Dive into the delicate flavors of sashimi, each piece a testament to the ocean's bounty. Or let the crispy allure of tempura, whether it's prawn or vegetables, dance on your palate. With every sip of Sake, these dishes come alive, echoing Japan's culinary artistry.<br><br></p>

        <div class="soju">
            <p class="title-soju">SOJU</p>
            <p class="vibe-soju">The Vibe: Vibrant Seoul streets, neon lights, and the rhythmic beats of K-pop in the distance.</p>
            <p class="content-soju">Perfect Pairings: Soju's spirited charm is the heart of Korean feasts. Imagine the sizzle of Korean BBQ, each morsel grilled to perfection, or the fiery embrace of a kimchi stew, warming your soul. With Soju by your side, every bite is a celebration of Korea's rich flavors and zest for life.<br><br></p>

        <div class="mijiu">
            <p class="title-mijiu">MIJIU</p>
            <p class="vibe-mijiu">The Vibe: Bustling Chinese markets, lanterns swaying, and the age-old wisdom of dynasties past.</p>
            <p class="content-mijiu">Perfect Pairings: Mijiu's subtle grace is the essence of Chinese delicacies. Dive into the world of dim sum, where each bite-sized delight is a culinary gem. Relish the crispy skin and tender meat of Peking duck, or let the sweet allure of mooncakes, symbolizing unity and prosperity, melt in your mouth. Mijiu elevates these dishes, weaving tales of China's rich gastronomic heritage.<br><br></p>

        <div class="ruou-can">
            <p class="title-ruou-can">RƯỢU CẦN</p>
            <p class="vibe-ruou-can">The Vibe: Lush Vietnamese rice paddies, the gentle hum of the Mekong, and the aroma of fresh herbs in the air.</p>
            <p class="content-ruou-can">Perfect Pairings: Rượu cần's enchanting spirit is a journey through Vietnam's culinary wonders. Delight in the fresh crunch of Vietnamese spring rolls, a burst of flavors and textures. Dive into a bowl of pho, its aromatic broth a symphony of spices. Or savor the smoky flavors of grilled fish, a testament to Vietnam's rich coastal bounty. With Rượu cần, every dish is a mosaic of flavors, celebrating Vietnam's culinary tapestry.<br><br></p>

        <div class="lao-lao">
            <p class="title-lao-lao">LAO-LAO</p>
            <p class="vibe-lao-lao">The Vibe: Tranquil Mekong sunsets, the distant chants from a monastery, and the warmth of Laotian smiles.</p>
            <p class="content-lao-lao">Perfect Pairings: Lao-Lao's earthy allure is the soul of Laotian feasts. Relish the flavors of Laap, a meat salad bursting with fresh herbs and spices. Let the comforting taste of sticky rice, a Laotian staple, complement your meal. Or explore the charred goodness of grilled vegetables, each bite a celebration of Laos' agrarian roots. Lao-Lao enhances these dishes, capturing the essence of Laotian hospitality and joy.<br><br></p>

        <div class="tapuy">
            <p class="title-tapuy">TAPUY</p>
            <p class="vibe-tapuy">The Vibe: Vibrant Filipino fiestas, the harmonious tunes of a rondalla, and the shimmering blue of the Pacific.</p>
            <p class="content-tapuy">Perfect Pairings: Tapuy, with its festive spirit, is the heart of Filipino celebrations. Dive into the crispy, golden skin of lechon, a feast for the senses. Savor the savory embrace of adobo, a dance of soy, vinegar, and spices. And for a sweet finale, let the layers of halo-halo, with its colorful medley of ingredients, delight your palate. With Tapuy, every dish is a toast to the Philippines' culinary mosaic and islander spirit.<br><br></p>
        </div>
        <p class="closing">From the serene shores of Japan to the bustling streets of Seoul, and from the vast landscapes of China to the vibrant fiestas of the Philippines, rice-based alcohols are a journey through cultures, traditions, and flavors. Each drink, with its unique taste profile, complements and elevates the dishes of its homeland, creating a harmonious blend of tastes and memories. So, as you embark on this culinary voyage, let the spirits guide you, and may your palate discover new horizons. Cheers to the world on a plate and in a glass! 🥂🍽️🌏</p>
        </div>
    </div>
</div>
