// src/app/main/about-main/about-main.component.ts
import { Component } from '@angular/core';
import { ViewportScroller } from '@angular/common';

@Component({
  selector: 'app-about-main',
  templateUrl: './about-main.component.html',
  styleUrls: ['./about-main.component.css']
})
export class AboutMainComponent {
  constructor(private viewportScroller: ViewportScroller) {}

  onLinkClick() {
    this.viewportScroller.scrollToPosition([0, 0]);
  }
}

<div class="container">
    <img src="/assets/images/main/about-main-images/cheers.jpg" alt="cheers image" class="image">
    <div class="background">
        <div class="text-content">
            <p class="heading">ABOUT US</p>
            <div class="content">
                <p class="description1">"Dive deep into the world of spirits and libations with us. From the rich history of whiskey to the subtle nuances of wine, our journey through the realm of alcohol is both enlightening and captivating. </p>
                <p class="description2">Curious? Discover more about our passionate team and our intoxicating quest for knowledge."</p>
                <a class="button" [routerLink]="['/about']" (click)="onLinkClick()">learn more</a>
            </div>
        </div>
    </div>
</div>

// src/components/main/AboutMain.tsx
import { Link } from 'react-router-dom';
import useScrollReveal from '../../hooks/useScrollReveal';
import './AboutMain.css';

export default function AboutMain() {
  const revealRef = useScrollReveal();

  return (
    <div className="container-about-main">
        <img src="/assets/images/main/about-main-images/cheers.jpg" alt="cheers image" className="image-about" />
        <div className="background-about" ref={revealRef}>
            <div className="text-content-about reveal reveal-right glass-panel">
                <p className="heading-about">THE SPIRIT OF ALHOCOOL</p>
                <div className="content-about">
                    <p className="description1-about">
                      "At Alhocool, every drop tells a story. We’re on a quest to demystify the world’s most iconic spirits, blending rich heritage with cutting-edge AI to bring you tales that are as intoxicating as the drinks themselves.
                    </p>
                    <p className="description2-about">
                      From the misty highlands of Scotland to the sun-drenched vineyards of Bordeaux, join us as we explore the essence of craftsmanship and the joy of shared knowledge."
                    </p>
                    <Link className="button-about btn-outline" to="/about" onClick={() => window.scrollTo(0, 0)}>discover our story</Link>
                </div>
            </div>
        </div>
    </div>
  );
}
