// src/components/blank/BlankPageContent.tsx
import './BlankPageContent.css';

export default function BlankPageContent() {
  return (
    <div className="blank-page-content-container">
        <p className="header">
            🍷 Oops! This blend isn't ready for tasting... just yet! 🍷
        </p>
        <p className="content">
            It seems you've uncorked a page that's still aging to perfection in our digital cellar. Our master web-vintners are carefully crafting this vintage, ensuring it'll be a delightful experience for you.
            <br/><br/>
            🍻 In the meantime, pour yourself a glass of patience, share a cheers with good company, and be sure to pop back in soon. We promise it'll be worth the wait! 🍻
        </p>
    </div>
  );
}

// src/app/blank/blank-page-content/blank-page-content.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-blank-page-content',
  templateUrl: './blank-page-content.component.html',
  styleUrls: ['./blank-page-content.component.css']
})
export class BlankPageContentComponent {

}

<div class="container">
    <p class="header">
        🍷 Oops! This blend isn't ready for tasting... just yet! 🍷
    </p>
    <p class="content">
        

It seems you've uncorked a page that's still aging to perfection in our digital cellar. Our master web-vintners are carefully crafting this vintage, ensuring it'll be a delightful experience for you.

🍻 In the meantime, pour yourself a glass of patience, share a cheers with good company, and be sure to pop back in soon. We promise it'll be worth the wait! 🍻
    </p>
</div>
