// src/components/spirit/SpiritProcess.tsx
import './SpiritProcess.css';

export default function SpiritProcess() {
  return (
    <div className="spirit-process-container">
        <p className="spirit-process-title">The Alchemical Art of Distilling Spirits:</p>
        <div className="spirit-process-content">

            <p className="title-whiskey">WHISKEY</p>
            <p className="content-whiskey">Whiskey, the golden nectar of poets and dreamers! It all starts with a harmonious blend of water, grain, and yeast. This trio is left to ferment, creating a bubbling concoction where sugars transform into alcohol, like a magical potion in the making.
                <br/><br/>
                The distillation process is where the real alchemy happens. The mash is heated, and as it sings steamy tunes, the vapors are captured and cooled, giving birth to whiskey. Those oak barrels? They're not just storage. They're where whiskey gets its wisdom, color, and character. Fun fact: The "angel's share" is the portion of whiskey that evaporates from the barrels during aging. So, next time you sip, remember you're sharing with the heavens!</p><br/>

            <p className="title-vodka">VODKA</p>
            <p className="content-vodka">Vodka, the crystal-clear enigma! Its origins are debated - Russia or Poland, but its making is pure art. Ingredients vary, from potatoes to grains to grapes, each giving vodka its unique soul. 
                <br/><br/>  
                Post-fermentation, it undergoes multiple distillations, each refining its spirit. The final touch? A luxurious spa treatment, filtered through charcoal, emerging pure and pristine. Did you know? Some premium vodkas are filtered through diamonds for that extra sparkle!</p><br/>

            <p className="title-rum">RUM</p>
            <p className="content-rum">Rum, the Caribbean's sun-kissed gift! Born in sugarcane fields, it's either fresh juice or molasses that gets the party started. Fermentation turns it spirited, ready for distillation.
                <br/><br/>    
                Some rums are bottled young, zesty, and lively, while others age gracefully in barrels, absorbing the wisdom of time. Pirate's secret: The older the rum, the richer the tales it tells!</p><br/>

            <p className="title-tequila">TEQUILA</p>
            <p className="content-tequila">Tequila, Mexico's liquid fiesta! The blue agave plant is its heart and soul. Harvested after a decade, its core or "piña" is roasted to release sweet nectars.
                <br/><br/>
                Fermentation and distillation follow, capturing the spirit of sun-soaked Mexican fields. Blanco or Añejo, each has a tale to tell. Fun tidbit: Real tequila doesn't come with a worm; that's a myth and mostly marketing!</p><br/>

            <p className="title-gin">GIN</p>
            <p className="content-gin">Gin, the botanical ballet in a bottle! It starts neutral but is transformed by juniper berries and a chorus of botanicals, each adding its note to the symphony.
                <br/><br/>
                Distilled with this botanical bouquet, gin emerges fragrant and flavorful. A gin-trivia for you: The classic "Gin & Tonic" was initially a medicinal drink to fight malaria. Cheers to good health!</p><br/>

            <p className="title-brandy">BRANDY</p>
            <p className="content-brandy">Brandy, the warming embrace in a glass! Whether it's wine or fruit juice, distillation concentrates its essence. Then, like a wise old sage, it rests in wooden casks, mellowing and deepening.
                <br/><br/>
                From apples to grapes, the fruit decides the flavor dance of the brandy. Here's a toast-worthy fact: The name "brandy" comes from "brandewijn," meaning "burnt wine." A poetic nod to the distillation process!</p><br/>

            <p className="closing">From fields to barrels to glasses, the journey of spirits is a tale of nature, time, and craftsmanship. As we toast to traditions and tales, let's savor the artistry in every drop. Here's to the alchemists of old and the joy they distilled for us! 🍸🍹🥃</p>
        </div>
    </div>
  );
}

// src/app/spirit/spirit-process/spirit-process.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-spirit-process',
  templateUrl: './spirit-process.component.html',
  styleUrls: ['./spirit-process.component.css']
})
export class SpiritProcessComponent {

}

<div class="container">
    <p class="title">The Alchemical Art of Distilling Spirits:</p>
    <div class="content">

        <p class="title-whiskey">WHISKEY</p>
        <p class="content-whiskey">Whiskey, the golden nectar of poets and dreamers! It all starts with a harmonious blend of water, grain, and yeast. This trio is left to ferment, creating a bubbling concoction where sugars transform into alcohol, like a magical potion in the making.
            <br><br>
            The distillation process is where the real alchemy happens. The mash is heated, and as it sings steamy tunes, the vapors are captured and cooled, giving birth to whiskey. Those oak barrels? They're not just storage. They're where whiskey gets its wisdom, color, and character. Fun fact: The "angel's share" is the portion of whiskey that evaporates from the barrels during aging. So, next time you sip, remember you're sharing with the heavens!</p><br>

        <p class="title-vodka">VODKA</p>
        <p class="content-vodka">Vodka, the crystal-clear enigma! Its origins are debated - Russia or Poland, but its making is pure art. Ingredients vary, from potatoes to grains to grapes, each giving vodka its unique soul. 
            <br><br>  
            Post-fermentation, it undergoes multiple distillations, each refining its spirit. The final touch? A luxurious spa treatment, filtered through charcoal, emerging pure and pristine. Did you know? Some premium vodkas are filtered through diamonds for that extra sparkle!</p><br>

        <p class="title-rum">RUM</p>
        <p class="content-rum">Rum, the Caribbean's sun-kissed gift! Born in sugarcane fields, it's either fresh juice or molasses that gets the party started. Fermentation turns it spirited, ready for distillation.
            <br><br>    
            Some rums are bottled young, zesty, and lively, while others age gracefully in barrels, absorbing the wisdom of time. Pirate's secret: The older the rum, the richer the tales it tells!</p><br>

        <p class="title-tequila">TEQUILA</p>
        <p class="content-tequila">Tequila, Mexico's liquid fiesta! The blue agave plant is its heart and soul. Harvested after a decade, its core or "piña" is roasted to release sweet nectars.
            <br><br>
            Fermentation and distillation follow, capturing the spirit of sun-soaked Mexican fields. Blanco or Añejo, each has a tale to tell. Fun tidbit: Real tequila doesn't come with a worm; that's a myth and mostly marketing!</p><br>

        <p class="title-gin">GIN</p>
        <p class="content-gin">Gin, the botanical ballet in a bottle! It starts neutral but is transformed by juniper berries and a chorus of botanicals, each adding its note to the symphony.
            <br><br>
            Distilled with this botanical bouquet, gin emerges fragrant and flavorful. A gin-trivia for you: The classic "Gin & Tonic" was initially a medicinal drink to fight malaria. Cheers to good health!</p><br>

        <p class="title-brandy">BRANDY</p>
        <p class="content-brandy">Brandy, the warming embrace in a glass! Whether it's wine or fruit juice, distillation concentrates its essence. Then, like a wise old sage, it rests in wooden casks, mellowing and deepening.
            <br><br>
            From apples to grapes, the fruit decides the flavor dance of the brandy. Here's a toast-worthy fact: The name "brandy" comes from "brandewijn," meaning "burnt wine." A poetic nod to the distillation process!</p><br>

        <p class="closing">From fields to barrels to glasses, the journey of spirits is a tale of nature, time, and craftsmanship. As we toast to traditions and tales, let's savor the artistry in every drop. Here's to the alchemists of old and the joy they distilled for us! 🍸🍹🥃</p>
    </div>
</div>
