// src/app/rice-alcohol/rice-alcohol-process/rice-alcohol-process.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-process',
  templateUrl: './rice-alcohol-process.component.html',
  styleUrls: ['./rice-alcohol-process.component.css']
})
export class RiceAlcoholProcessComponent {

}

<div class="container">
    <p class="title">Rice's Grand Odyssey: A Deep Dive into Liquid Gold!</p>
    <div class="content">

        <p class="title-sake">SAKE</p>
        <p class="content-sake">Sake, the pride of Japan, is a meticulous blend of art and science. The rice, specifically sake rice, is polished to remove the bran, sometimes up to 50% of its original size! After steaming, the rice meets koji mold, which is cultivated in dedicated koji rooms. This mold not only converts starch to sugar but also imparts unique flavors. Multiple parallel fermentations occur in large tanks, where yeast transforms sugar into alcohol while koji continues its saccharification. The moromi (mash) is then pressed, and the liquid is separated from the rice solids. Some sakes even undergo pasteurization twice! The final product can vary from sweet to dry, light to robust, based on the brewing techniques. 🍚🔬🎨</p><br>

        <p class="title-soju">SOJU</p>
        <p class="content-soju">Soju, Korea's iconic spirit, often starts with a base of rice, barley, or sweet potatoes. Modern Soju production uses continuous column distillation, ensuring a high alcohol content. The spirit is then diluted with water, and sometimes, sweeteners, flavorings, or even herbs are added. Traditional Soju, however, is made using single distillation, retaining more flavors and producing a smoother texture. It's a drink that has evolved with Korea's history, from royal courts to bustling streets. 🌃🍸</p><br>

        <p class="title-mijiu">MIJIU</p>
        <p class="content-mijiu">Mijiu, China's sweet nectar, often uses glutinous rice. The 'qu' used in fermentation is unique, as it contains both molds and yeasts, facilitating simultaneous saccharification and fermentation. This process can occur in various vessels, from ceramic jars to wooden vats. Aging is crucial for Mijiu, with some variants being aged for decades, resulting in a richer flavor and deeper color. 🏺🌟</p><br>

        <p class="title-roucan">ROU CAN</p>
        <p class="content-roucan">Rou Can, a gem from Taiwan, is distilled from fermented rice. The fermentation process is shorter compared to other rice alcohols, leading to a fresh and robust flavor. The distillation process captures the essence of the rice, producing a clear spirit that's both potent and flavorful. 🌪️🍶</p><br>

        <p class="title-laolao">LAO LAO</p>
        <p class="content-laolao">Lao Lao, Laos' rustic charm, is made in villages across the country. The sticky rice is first steamed in bamboo containers over wood fires. After cooling, it's mixed with yeast and left to ferment in earthen jars. Distillation is often done in homemade stills, capturing the strong spirit while leaving behind the rice solids. Each village might have its unique twist, making Lao Lao a drink of diverse flavors and tales. 🌲🔥</p><br>

        <p class="title-tapuy">TAPUY</p>
        <p class="content-tapuy">Tapuy, hailing from the Philippines, is a celebration of simplicity. The glutinous rice is first cooked, then mixed with 'bubod', a traditional fermentation starter. This mixture is wrapped in leaves, often banana or palm, and left to ferment. The result is a mildly alcoholic paste. It's not just the drink but the communal gatherings, the shared stories, and the age-old traditions that make Tapuy truly special. 🌿🎉</p><br>

        <p class="closing">Rice, in its journey from fields to flasks, undergoes magical transformations. Each country, each region, and sometimes each village, has its unique take on rice alcohol, reflecting its history, culture, and environment. As we savor these drinks, we're not just tasting flavors but also stories, traditions, and the passion of countless brewers. So, here's to rice, the grain that unites us in spirit(s)! 🍶🌏❤️</p>
    </div>
</div>

// src/components/rice-alcohol/RiceAlcoholProcess.tsx
import './RiceAlcoholProcess.css';

export default function RiceAlcoholProcess() {
  return (
    <div className="rice-alcohol-process-container">
        <p className="rice-alcohol-process-title">Rice's Grand Odyssey: A Deep Dive into Liquid Gold!</p>
        <div className="rice-alcohol-process-content">

            <p className="title-sake">SAKE</p>
            <p className="content-sake">Sake, the pride of Japan, is a meticulous blend of art and science. The rice, specifically sake rice, is polished to remove the bran, sometimes up to 50% of its original size! After steaming, the rice meets koji mold, which is cultivated in dedicated koji rooms. This mold not only converts starch to sugar but also imparts unique flavors. Multiple parallel fermentations occur in large tanks, where yeast transforms sugar into alcohol while koji continues its saccharification. The moromi (mash) is then pressed, and the liquid is separated from the rice solids. Some sakes even undergo pasteurization twice! The final product can vary from sweet to dry, light to robust, based on the brewing techniques. 🍚🔬🎨</p><br/>

            <p className="title-soju">SOJU</p>
            <p className="content-soju">Soju, Korea's iconic spirit, often starts with a base of rice, barley, or sweet potatoes. Modern Soju production uses continuous column distillation, ensuring a high alcohol content. The spirit is then diluted with water, and sometimes, sweeteners, flavorings, or even herbs are added. Traditional Soju, however, is made using single distillation, retaining more flavors and producing a smoother texture. It's a drink that has evolved with Korea's history, from royal courts to bustling streets. 🌃🍸</p><br/>

            <p className="title-mijiu">MIJIU</p>
            <p className="content-mijiu">Mijiu, China's sweet nectar, often uses glutinous rice. The 'qu' used in fermentation is unique, as it contains both molds and yeasts, facilitating simultaneous saccharification and fermentation. This process can occur in various vessels, from ceramic jars to wooden vats. Aging is crucial for Mijiu, with some variants being aged for decades, resulting in a richer flavor and deeper color. 🏺🌟</p><br/>

            <p className="title-roucan">ROU CAN</p>
            <p className="content-roucan">Rou Can, a gem from Taiwan, is distilled from fermented rice. The fermentation process is shorter compared to other rice alcohols, leading to a fresh and robust flavor. The distillation process captures the essence of the rice, producing a clear spirit that's both potent and flavorful. 🌪️🍶</p><br/>

            <p className="title-laolao">LAO LAO</p>
            <p className="content-laolao">Lao Lao, Laos' rustic charm, is made in villages across the country. The sticky rice is first steamed in bamboo containers over wood fires. After cooling, it's mixed with yeast and left to ferment in earthen jars. Distillation is often done in homemade stills, capturing the strong spirit while leaving behind the rice solids. Each village might have its unique twist, making Lao Lao a drink of diverse flavors and tales. 🌲🔥</p><br/>

            <p className="title-tapuy">TAPUY</p>
            <p className="content-tapuy">Tapuy, hailing from the Philippines, is a celebration of simplicity. The glutinous rice is first cooked, then mixed with 'bubod', a traditional fermentation starter. This mixture is wrapped in leaves, often banana or palm, and left to ferment. The result is a mildly alcoholic paste. It's not just the drink but the communal gatherings, the shared stories, and the age-old traditions that make Tapuy truly special. 🌿🎉</p><br/>

            <p className="closing">Rice, in its journey from fields to flasks, undergoes magical transformations. Each country, each region, and sometimes each village, has its unique take on rice alcohol, reflecting its history, culture, and environment. As we savor these drinks, we're not just tasting flavors but also stories, traditions, and the passion of countless brewers. So, here's to rice, the grain that unites us in spirit(s)! 🍶🌏❤️</p>
        </div>
    </div>
  );
}
