// src/app/rice-alcohol/rice-alcohol-title/rice-alcohol-title.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-title',
  templateUrl: './rice-alcohol-title.component.html',
  styleUrls: ['./rice-alcohol-title.component.css']
})
export class RiceAlcoholTitleComponent {

}

<div class="container">
    <img src="/assets/images/rice-alcohol-images/rice-alcohol-title.jpg" alt="rice-alcohol-image" class="rice-alcohol-image">
    <p class="title">RICE BASED<br> ALCOHOLS</p>
</div>

// src/components/rice-alcohol/RiceAlcoholTitle.tsx
import './RiceAlcoholTitle.css';

export default function RiceAlcoholTitle() {
  return (
    <div className="rice-alcohol-title-container">
        <img src="/assets/images/rice-alcohol-images/rice-alcohol-title.jpg" alt="rice-alcohol-image" className="rice-alcohol-image" />
        <p className="title">RICE BASED<br/> ALCOHOLS</p>
    </div>
  );
}
