// src/app/rice-alcohol/rice-alcohol-overview/rice-alcohol-overview.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-overview',
  templateUrl: './rice-alcohol-overview.component.html',
  styleUrls: ['./rice-alcohol-overview.component.css']
})
export class RiceAlcoholOverviewComponent {

}

<div class="container">
    <p class="title">The Ricey Revelations:</p>
    <p class="content">In a realm where vast fields of golden grains swayed with the wind, a culinary conundrum arose: "How do we transform this humble grain into a drink fit for the gods?" And thus, rice-based alcohols were born, answering the universe's call for a silky-smooth sipper!<br>
            <br>   
            Now, let's dive deep into this liquid gold. Rice, the staple that once dreamt of being the star of every dinner plate, had bigger aspirations. It whispered, "Why be just a side dish when I can be the life of the party?" And so, it embarked on a journey to become the soul of some of the world's most cherished beverages.<br>
            <br>            
            But rice wasn't alone in this spirited adventure. It was bathed in pristine waters, nurtured by the sun, and serenaded by the winds. Then came the mold, Aspergillus oryzae, a magical microbe that transformed the starches into sugars. And of course, yeast joined the party, turning those sugars into alcohol, crafting a potion that was both potent and pleasant.<br>
            <br>            
            From the aromatic Sake of Japan, with its delicate dance of flavors, to the robust Makgeolli of Korea, a milky marvel that's both tangy and sweet. And let's not forget China's Mijiu, a clear and crisp concoction, or Vietnam's Rượu cần, traditionally sipped from long bamboo straws in communal joy. Each drink, a testament to the versatility of rice and the cultures that revered it.<br>
            <br>            
            As these beverages flowed from village gatherings to royal feasts, they wove tales of celebration, unity, and heritage. And that, dear reader, is the saga of rice-based alcohols, the elixirs that captured hearts and spirits across the globe with their elegance and essence.
        </p>
</div>

// src/components/rice-alcohol/RiceAlcoholOverview.tsx
import './RiceAlcoholOverview.css';

export default function RiceAlcoholOverview() {
  return (
    <div className="rice-alcohol-overview-container">
        <p className="rice-alcohol-overview-title">The Ricey Revelations:</p>
        <p className="rice-alcohol-overview-content">In a realm where vast fields of golden grains swayed with the wind, a culinary conundrum arose: "How do we transform this humble grain into a drink fit for the gods?" And thus, rice-based alcohols were born, answering the universe's call for a silky-smooth sipper!<br/>
            <br/>   
            Now, let's dive deep into this liquid gold. Rice, the staple that once dreamt of being the star of every dinner plate, had bigger aspirations. It whispered, "Why be just a side dish when I can be the life of the party?" And so, it embarked on a journey to become the soul of some of the world's most cherished beverages.<br/>
            <br/>            
            But rice wasn't alone in this spirited adventure. It was bathed in pristine waters, nurtured by the sun, and serenaded by the winds. Then came the mold, Aspergillus oryzae, a magical microbe that transformed the starches into sugars. And of course, yeast joined the party, turning those sugars into alcohol, crafting a potion that was both potent and pleasant.<br/>
            <br/>            
            From the aromatic Sake of Japan, with its delicate dance of flavors, to the robust Makgeolli of Korea, a milky marvel that's both tangy and sweet. And let's not forget China's Mijiu, a clear and crisp concoction, or Vietnam's Rượu cần, traditionally sipped from long bamboo straws in communal joy. Each drink, a testament to the versatility of rice and the cultures that revered it.<br/>
            <br/>            
            As these beverages flowed from village gatherings to royal feasts, they wove tales of celebration, unity, and heritage. And that, dear reader, is the saga of rice-based alcohols, the elixirs that captured hearts and spirits across the globe with their elegance and essence.
        </p>
    </div>
  );
}
