// src/app/beer/beer-history/beer-history.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-beer-history',
  templateUrl: './beer-history.component.html',
  styleUrls: ['./beer-history.component.css']
})
export class BeerHistoryComponent {

}

<div class="container">
    <p class="title">
        A Frothy Journey Through Time</p>
    <div class="content">
        <p class="p1">
            Let's rewind the clock to around 5,000 BC, when the ancient Sumerians of Mesopotamia stumbled upon a happy accident. Picture this: some grains left out in the rain, fermenting into a delightful, bubbly concoction. The world's first beer! These ingenious folks not only enjoyed their newfound beverage but even dedicated a hymn to Ninkasi, the goddess of brewing. Talk about fanfare!
        <br><br></p>
        <p class="p2">
            Fast forward to ancient Egypt, where beer wasn't just a casual drink; it was liquid gold! The Egyptians believed beer was a gift from the gods (and who could blame them?). It was consumed daily, by everyone from pharaohs to peasants. Fun fact: workers who built the pyramids were often paid in beer. That's right, liquid wages! And let's not forget the ancient Egyptian women, who were the primary brewers and even had a special goddess, Tenenit, overseeing their brewing activities.
            <br><br></p>
        <p class="p3">
            As centuries rolled on, beer made its frothy mark across civilizations. The Romans, though wine enthusiasts, couldn't resist the allure of beer, which they called "cerevisia." Meanwhile, in medieval Europe, monasteries became the brewing hotspots. Monks, with their meticulous methods, refined brewing techniques, and even introduced hops to the mix. These holy men believed that just as bread was the body of Christ, beer was liquid bread, a gift to humanity. And let's be honest, who wouldn't want to attend a sermon with a pint in hand?
            <br><br></p>
        <p class="p4">
            The Industrial Revolution in the 18th and 19th centuries gave beer a modern twist. With the invention of the steam engine, beer production scaled up, and bottling became a breeze. The world also saw the birth of the pale ale during this period, thanks to the advent of new malting techniques. And in the land of the free, American brewers introduced corn and rice to the brewing process, giving birth to the American-style lager. The beer landscape was buzzing with innovation!
            <br><br></p>
        <p class="p5">
            Today, beer stands tall and frothy as one of the world's most beloved beverages. The craft beer movement has taken the globe by storm, with microbreweries experimenting with flavors from coffee to chili peppers. Beer festivals, Oktoberfests, and brewery tours are testament to beer's unwavering popularity. From its ancient, accidental origins to the craft beer renaissance of today, beer's journey is a testament to humanity's love for a good brew. So, here's to beer – a drink steeped in history, frothing with fun, and forever young!
            <br><br></p>
    </div>
        
</div>

// src/components/beer/BeerHistory.tsx
import './BeerHistory.css';

export default function BeerHistory() {
  return (
    <div className="beer-history-container">
        <p className="beer-history-title">
            A Frothy Journey Through Time</p>
        <div className="beer-history-content">
            <p className="p1">
                Let's rewind the clock to around 5,000 BC, when the ancient Sumerians of Mesopotamia stumbled upon a happy accident. Picture this: some grains left out in the rain, fermenting into a delightful, bubbly concoction. The world's first beer! These ingenious folks not only enjoyed their newfound beverage but even dedicated a hymn to Ninkasi, the goddess of brewing. Talk about fanfare!
            <br/><br/></p>
            <p className="p2">
                Fast forward to ancient Egypt, where beer wasn't just a casual drink; it was liquid gold! The Egyptians believed beer was a gift from the gods (and who could blame them?). It was consumed daily, by everyone from pharaohs to peasants. Fun fact: workers who built the pyramids were often paid in beer. That's right, liquid wages! And let's not forget the ancient Egyptian women, who were the primary brewers and even had a special goddess, Tenenit, overseeing their brewing activities.
                <br/><br/></p>
            <p className="p3">
                As centuries rolled on, beer made its frothy mark across civilizations. The Romans, though wine enthusiasts, couldn't resist the allure of beer, which they called "cerevisia." Meanwhile, in medieval Europe, monasteries became the brewing hotspots. Monks, with their meticulous methods, refined brewing techniques, and even introduced hops to the mix. These holy men believed that just as bread was the body of Christ, beer was liquid bread, a gift to humanity. And let's be honest, who wouldn't want to attend a sermon with a pint in hand?
                <br/><br/></p>
            <p className="p4">
                The Industrial Revolution in the 18th and 19th centuries gave beer a modern twist. With the invention of the steam engine, beer production scaled up, and bottling became a breeze. The world also saw the birth of the pale ale during this period, thanks to the advent of new malting techniques. And in the land of the free, American brewers introduced corn and rice to the brewing process, giving birth to the American-style lager. The beer landscape was buzzing with innovation!
                <br/><br/></p>
            <p className="p5">
                Today, beer stands tall and frothy as one of the world's most beloved beverages. The craft beer movement has taken the globe by storm, with microbreweries experimenting with flavors from coffee to chili peppers. Beer festivals, Oktoberfests, and brewery tours are testament to beer's unwavering popularity. From its ancient, accidental origins to the craft beer renaissance of today, beer's journey is a testament to humanity's love for a good brew. So, here's to beer – a drink steeped in history, frothing with fun, and forever young!
                <br/><br/></p>
        </div>
    </div>
  );
}
