// src/app/beer/beer-food/beer-food.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-beer-food',
  templateUrl: './beer-food.component.html',
  styleUrls: ['./beer-food.component.css']
})
export class BeerFoodComponent {

}

<div class="container">
    <p class="title">The Perfect Pair: Beer & Bites</p>
    <div class="content">
        <div class="lagner">
            <p class="title-lagner">LAGNER</p>
            <p class="vibe-lagner"> The Vibe: Sunny afternoons, laughter in the air, and a laid-back picnic setting.</p>
            <p class="content-lagner">Perfect Pairings: Lager's light and bubbly nature make it the ideal companion for sun-soaked picnics. Imagine peeling a shrimp from a fresh cocktail, taking a bite of a crisp summer salad drizzled with a tangy vinaigrette, or savoring the zesty flavors of lemon grilled chicken. The refreshing taste of Lager enhances the flavors, making every bite a summer dream.<br><br></p>

        <div class="ale">
            <p class="title-ale">ALE</p>
            <p class="vibe-ale">The Vibe: Bold, robust, and full of character, much like a family gathering around a BBQ.</p>
            <p class="content-ale">Perfect Pairings: Ale's diverse flavor profile calls for dishes that pack a punch. Smoked BBQ ribs with a side of tangy coleslaw, a loaded deep-dish pizza with all your favorite toppings, or a hearty shepherd's pie with a golden crust. The richness of Ale complements these dishes, creating a hearty meal that satisfies the soul.<br><br></p>

        <div class="stout">
            <p class="title-stout">STOUT</p>
            <p class="vibe-stout">The Vibe: Cozy winter evenings, a crackling fireplace, and the comforting embrace of loved ones.</p>
            <p class="content-stout">Perfect Pairings: Stout, with its deep and intense flavors, is a match made in heaven for cold nights. Slow-cooked meats that melt in the mouth, a rich beef stew, or a lamb roast. And for dessert? A gooey chocolate lava cake or a creamy tiramisu. Stout's roasted undertones enhance the flavors, making every bite a warm hug.<br><br></p>

        <div class="ipa">
            <p class="title-ipa">INDIA PALE ALE(IPA)</p>
            <p class="vibe-ipa">The Vibe: A vibrant carnival, a burst of colors, and a celebration of life.</p>
            <p class="content-ipa">Perfect Pairings: IPA's hoppy bitterness is a canvas for spicy and tangy dishes. Spicy Thai green curry, tangy tandoori chicken straight from the clay oven, or a juicy blue cheese burger with caramelized onions. The bold flavors of IPA stand up to these dishes, creating a taste explosion with every sip and bite.<br><br></p>

        <div class="pilsner">
            <p class="title-pilsner">PILSNER</p>
            <p class="vibe-pilsner">The Vibe: Elegant soirées, soft jazz playing in the background, and a touch of sophistication.</p>
            <p class="content-pilsner">Perfect Pairings: Pilsner's delicate and crisp taste is the star of exquisite evenings. Freshly shucked oysters with a dash of lemon, creamy mushroom risotto topped with parmesan, or a delicate ceviche with citrusy notes. Pilsner adds a touch of elegance, elevating the dining experience.<br><br></p>

        <div class="wheat-beer">
            <p class="title-wheat-beer">WHEAT BEER</p>
                <p class="vibe-wheat-beer">The Vibe: Sunday brunches, sunlit patios, and the joy of leisurely mornings.</p>
                <p class="content-wheat-beer">Perfect Pairings: Wheat Beer, with its light and fruity undertones, is the toast of brunch classics. Creamy eggs benedict with a side of hollandaise, crunchy avocado toast sprinkled with chili flakes, or a light lemon tart with a buttery crust. Wheat Beer's effervescence adds a sparkle, making every brunch a delightful affair.<br><br></p>
        </div>
        <p class="closing">From sun-soaked picnics to elegant evening dinners, beer has proven to be the perfect companion to a myriad of culinary delights. Each type of beer, with its unique flavor profile, complements and elevates the dishes it's paired with, creating a symphony of tastes on the palate. Whether it's the zest of an IPA with spicy curries or the smoothness of a Stout with rich desserts, the right beer pairing transforms a meal into an unforgettable experience. So, the next time you set the table, remember to invite beer to the feast. Here's to the harmonious dance of flavors and the joy of epicurean encounters! 🍻🍽️🎉</p>
        </div>
    
</div>

// src/components/beer/BeerFood.tsx
import './BeerFood.css';

export default function BeerFood() {
  return (
    <div className="beer-food-container">
        <p className="beer-food-title">The Perfect Pair: Beer & Bites</p>
        <div className="beer-food-content">
            <div className="lagner">
                <p className="title-lagner">LAGNER</p>
                <p className="vibe-lagner"> The Vibe: Sunny afternoons, laughter in the air, and a laid-back picnic setting.</p>
                <p className="content-lagner">Perfect Pairings: Lager's light and bubbly nature make it the ideal companion for sun-soaked picnics. Imagine peeling a shrimp from a fresh cocktail, taking a bite of a crisp summer salad drizzled with a tangy vinaigrette, or savoring the zesty flavors of lemon grilled chicken. The refreshing taste of Lager enhances the flavors, making every bite a summer dream.<br/><br/></p>
            </div>
            <div className="ale">
                <p className="title-ale">ALE</p>
                <p className="vibe-ale">The Vibe: Bold, robust, and full of character, much like a family gathering around a BBQ.</p>
                <p className="content-ale">Perfect Pairings: Ale's diverse flavor profile calls for dishes that pack a punch. Smoked BBQ ribs with a side of tangy coleslaw, a loaded deep-dish pizza with all your favorite toppings, or a hearty shepherd's pie with a golden crust. The richness of Ale complements these dishes, creating a hearty meal that satisfies the soul.<br/><br/></p>
            </div>

            <div className="stout">
                <p className="title-stout">STOUT</p>
                <p className="vibe-stout">The Vibe: Cozy winter evenings, a crackling fireplace, and the comforting embrace of loved ones.</p>
                <p className="content-stout">Perfect Pairings: Stout, with its deep and intense flavors, is a match made in heaven for cold nights. Slow-cooked meats that melt in the mouth, a rich beef stew, or a lamb roast. And for dessert? A gooey chocolate lava cake or a creamy tiramisu. Stout's roasted undertones enhance the flavors, making every bite a warm hug.<br/><br/></p>
            </div>

            <div className="ipa">
                <p className="title-ipa">INDIA PALE ALE(IPA)</p>
                <p className="vibe-ipa">The Vibe: A vibrant carnival, a burst of colors, and a celebration of life.</p>
                <p className="content-ipa">Perfect Pairings: IPA's hoppy bitterness is a canvas for spicy and tangy dishes. Spicy Thai green curry, tangy tandoori chicken straight from the clay oven, or a juicy blue cheese burger with caramelized onions. The bold flavors of IPA stand up to these dishes, creating a taste explosion with every sip and bite.<br/><br/></p>
            </div>

            <div className="pilsner">
                <p className="title-pilsner">PILSNER</p>
                <p className="vibe-pilsner">The Vibe: Elegant soirées, soft jazz playing in the background, and a touch of sophistication.</p>
                <p className="content-pilsner">Perfect Pairings: Pilsner's delicate and crisp taste is the star of exquisite evenings. Freshly shucked oysters with a dash of lemon, creamy mushroom risotto topped with parmesan, or a delicate ceviche with citrusy notes. Pilsner adds a touch of elegance, elevating the dining experience.<br/><br/></p>
            </div>

            <div className="wheat-beer">
                <p className="title-wheat-beer">WHEAT BEER</p>
                <p className="vibe-wheat-beer">The Vibe: Sunday brunches, sunlit patios, and the joy of leisurely mornings.</p>
                <p className="content-wheat-beer">Perfect Pairings: Wheat Beer, with its light and fruity undertones, is the toast of brunch classics. Creamy eggs benedict with a side of hollandaise, crunchy avocado toast sprinkled with chili flakes, or a light lemon tart with a buttery crust. Wheat Beer's effervescence adds a sparkle, making every brunch a delightful affair.<br/><br/></p>
            </div>
            
            <p className="closing">From sun-soaked picnics to elegant evening dinners, beer has proven to be the perfect companion to a myriad of culinary delights. Each type of beer, with its unique flavor profile, complements and elevates the dishes it's paired with, creating a symphony of tastes on the palate. Whether it's the zest of an IPA with spicy curries or the smoothness of a Stout with rich desserts, the right beer pairing transforms a meal into an unforgettable experience. So, the next time you set the table, remember to invite beer to the feast. Here's to the harmonious dance of flavors and the joy of epicurean encounters! 🍻🍽️🎉</p>
        </div>
    </div>
  );
}
