// src/components/wine/WineFood.tsx
import './WineFood.css';

export default function WineFood() {
  return (
    <div className="wine-food-container">
        <p className="wine-food-title">The Perfect Pair: Wine & Dishes</p>
        <div className="wine-food-content">

            <div className="red-wine">
                <p className="title-red">Red Wine:</p>
                <p className="vibe-red">The Vibe: Romantic candlelit dinners, soft jazz in the background, and intimate conversations.</p>
                <p className="content-red">Red wine, with its deep hues and robust flavors, is the ideal companion to hearty dishes. Imagine savoring a perfectly cooked steak, its juices melding with the rich notes of a Cabernet Sauvignon. Pasta dishes, especially those with rich tomato or meat sauces, find their match in red wines like Merlot or Chianti. And for those with a sweet tooth, the surprising pairing of dark chocolate truffles with a glass of red can be a delightful experience, with the bitterness of the chocolate enhancing the wine's fruity undertones.</p><br/>
            </div>

            <div className="white-wine">
                <p className="title-white">White Wine:</p>
                <p className="vibe-white">The Vibe: Beachside luncheons, gentle sea breezes, and the sound of waves crashing.</p>
                <p className="content-white">White wine, often celebrated for its light and crisp flavors, pairs best with dishes that carry a hint of delicacy. Seafood dishes, whether it's a creamy lobster bisque or grilled salmon, are elevated when accompanied by a chilled Chardonnay or Sauvignon Blanc. Poultry dishes, especially chicken in creamy sauces, harmonize with the subtle notes of white wines. And for a refreshing appetizer, a cheese platter featuring soft cheeses like goat and feta, paired with a Pinot Grigio, sets the tone for a delightful meal.</p><br/>
            </div>

            <div className="rose">
                <p className="title-rose">Rosé:</p>
                <p className="vibe-rose">The Vibe: Garden parties, floral dresses, and laughter under the sun.</p>
                <p className="content-rose">Rosé, with its beautiful pink hue, is the picnic champion. Envision a sunny day, a basket filled with strawberry salads with a hint of balsamic, grilled prawns marinated in herbs, or a Mediterranean mezze with olives, hummus, and pita. The fruity and floral notes of a Rosé complement these dishes, making every bite feel like a summer's day.</p><br/>
            </div>

            <div className="sparkling-wine">
                <p className="title-sparkling">Sparkling Wine:</p>
                <p className="vibe-sparkling">The Vibe: Grand celebrations, twinkling lights, and the sound of glasses clinking.</p>
                <p className="content-sparkling">Sparkling wine, synonymous with celebrations, is versatile in its pairings. The effervescence of a Prosecco or Champagne is a match for oysters, their bubbles enhancing the oceanic flavors. Sushi, with its mix of textures and flavors, dances beautifully with the crispness of sparkling wine. And for a fun twist, pairing it with salty fries brings out a play of flavors, the saltiness contrasting with the wine's sweetness.</p><br/>
            </div>

            <div className="dessert">
                <p className="title-dessert">Dessert Wine:</p>
                <p className="vibe-dessert">The Vibe: Cozy evenings, a good book in hand, and the warmth of a fireplace.</p>
                <p className="content-dessert">Dessert wines, as the name suggests, are a treat. Their sweetness and richness make them the perfect ending to a meal. A Port or Muscat paired with blue cheese creates a symphony of flavors, the sweetness of the wine cutting through the cheese's sharpness. Foie gras, with its creamy texture, finds its match in a Sauternes. And for dessert, whether it's a gooey chocolate cake or a fruit tart, a glass of dessert wine elevates the experience to pure indulgence.</p><br/>
            </div>

            <div className="fortified">
                <p className="title-fortified">Fortified Wine:</p>
                <p className="vibe-fortified">The Vibe: Vintage lounges, leather armchairs, and the rich aroma of history.</p>
                <p className="content-fortified">Fortified wines, with their added spirits, are intense and flavorful. Think of a Sherry or Madeira, their flavors deep and complex. They're perfect with hard cheeses, the wine's intensity complementing the cheese's aged flavors. Nuts, especially almonds or walnuts, paired with a fortified wine, make for a delightful snack. And for dessert, rich, fruity puddings or tarts find their match in the wine's depth.</p><br/>
            </div>

            <p className="closing">From elegant dinners to sunlit picnics, wine has proven to be the perfect companion to a myriad of culinary delights. Each type of wine, with its unique flavor profile, complements and elevates the dishes it's paired with, creating a symphony of tastes on the palate. Whether it's the robustness of a Red with steak or the sweetness of a Dessert Wine with pastries, the right wine pairing transforms a meal into an unforgettable experience. So, the next time you set the table, remember to invite wine to the feast. Here's to the harmonious dance of flavors and the joy of epicurean encounters! 🍷🍽️🎉</p>
        </div>
    </div>
  );
}

// src/app/wine/wine-food/wine-food.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-food',
  templateUrl: './wine-food.component.html',
  styleUrls: ['./wine-food.component.css']
})
export class WineFoodComponent {

}

<div class="container">
    <p class="title">The Perfect Pair: Wine & Dishes</p>
    <div class="content">

        <div class="red-wine">
            <p class="title-red">Red Wine:</p>
            <p class="vibe-red">The Vibe: Romantic candlelit dinners, soft jazz in the background, and intimate conversations.</p>
            <p class="content-red">Red wine, with its deep hues and robust flavors, is the ideal companion to hearty dishes. Imagine savoring a perfectly cooked steak, its juices melding with the rich notes of a Cabernet Sauvignon. Pasta dishes, especially those with rich tomato or meat sauces, find their match in red wines like Merlot or Chianti. And for those with a sweet tooth, the surprising pairing of dark chocolate truffles with a glass of red can be a delightful experience, with the bitterness of the chocolate enhancing the wine's fruity undertones.</p><br>
        </div>

        <div class="white-wine">
            <p class="title-white">White Wine:</p>
            <p class="vibe-white">The Vibe: Beachside luncheons, gentle sea breezes, and the sound of waves crashing.</p>
            <p class="content-white">White wine, often celebrated for its light and crisp flavors, pairs best with dishes that carry a hint of delicacy. Seafood dishes, whether it's a creamy lobster bisque or grilled salmon, are elevated when accompanied by a chilled Chardonnay or Sauvignon Blanc. Poultry dishes, especially chicken in creamy sauces, harmonize with the subtle notes of white wines. And for a refreshing appetizer, a cheese platter featuring soft cheeses like goat and feta, paired with a Pinot Grigio, sets the tone for a delightful meal.</p><br>
        </div>

        <div class="rose">
            <p class="title-rose">Rosé:</p>
            <p class="vibe-rose">The Vibe: Garden parties, floral dresses, and laughter under the sun.</p>
            <p class="content-rose">Rosé, with its beautiful pink hue, is the picnic champion. Envision a sunny day, a basket filled with strawberry salads with a hint of balsamic, grilled prawns marinated in herbs, or a Mediterranean mezze with olives, hummus, and pita. The fruity and floral notes of a Rosé complement these dishes, making every bite feel like a summer's day.</p><br>
        </div>

        <div class="sparkling-wine">
            <p class="title-sparkling">Sparkling Wine:</p>
            <p class="vibe-sparkling">The Vibe: Grand celebrations, twinkling lights, and the sound of glasses clinking.</p>
            <p class="content-sparkling">Sparkling wine, synonymous with celebrations, is versatile in its pairings. The effervescence of a Prosecco or Champagne is a match for oysters, their bubbles enhancing the oceanic flavors. Sushi, with its mix of textures and flavors, dances beautifully with the crispness of sparkling wine. And for a fun twist, pairing it with salty fries brings out a play of flavors, the saltiness contrasting with the wine's sweetness.</p><br>
        </div>

        <div class="dessert">
            <p class="title-dessert">Dessert Wine:</p>
            <p class="vibe-dessert">The Vibe: Cozy evenings, a good book in hand, and the warmth of a fireplace.</p>
            <p class="content-dessert">Dessert wines, as the name suggests, are a treat. Their sweetness and richness make them the perfect ending to a meal. A Port or Muscat paired with blue cheese creates a symphony of flavors, the sweetness of the wine cutting through the cheese's sharpness. Foie gras, with its creamy texture, finds its match in a Sauternes. And for dessert, whether it's a gooey chocolate cake or a fruit tart, a glass of dessert wine elevates the experience to pure indulgence.</p><br>
        </div>

        <div class="fortified">
            <p class="title-fortified">Fortified Wine:</p>
            <p class="vibe-fortified">The Vibe: Vintage lounges, leather armchairs, and the rich aroma of history.</p>
            <p class="content-fortified">Fortified wines, with their added spirits, are intense and flavorful. Think of a Sherry or Madeira, their flavors deep and complex. They're perfect with hard cheeses, the wine's intensity complementing the cheese's aged flavors. Nuts, especially almonds or walnuts, paired with a fortified wine, make for a delightful snack. And for dessert, rich, fruity puddings or tarts find their match in the wine's depth.</p><br>
        </div>

        <p class="closing">From elegant dinners to sunlit picnics, wine has proven to be the perfect companion to a myriad of culinary delights. Each type of wine, with its unique flavor profile, complements and elevates the dishes it's paired with, creating a symphony of tastes on the palate. Whether it's the robustness of a Red with steak or the sweetness of a Dessert Wine with pastries, the right wine pairing transforms a meal into an unforgettable experience. So, the next time you set the table, remember to invite wine to the feast. Here's to the harmonious dance of flavors and the joy of epicurean encounters! 🍷🍽️🎉</p>
    </div>
</div>
