// src/components/login/LoginSignup.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth } from '../../firebase';
import { signInWithEmailAndPassword, createUserWithEmailAndPassword } from 'firebase/auth';
import './LoginSignup.css';

export default function LoginSignup() {
  const [isLoginMode, setIsLoginMode] = useState(true);
  const [errorMessage, setErrorMessage] = useState('');
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  
  const navigate = useNavigate();

  const switchMode = (loginMode: boolean) => {
    setIsLoginMode(loginMode);
    setErrorMessage('');
  };

  const login = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || password.length < 6) return;
    
    try {
      await signInWithEmailAndPassword(auth, email, password);
      navigate('/main');
    } catch (error: any) {
      if (error.code === 'auth/wrong-password' || error.code === 'auth/user-not-found') {
        setErrorMessage('Incorrect username or password');
      } else {
        setErrorMessage(error.message);
      }
    }
  };

  const signup = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || password.length < 6 || confirmPassword.length < 6) return;
    
    if (password !== confirmPassword) {
      setErrorMessage('Passwords do not match');
      return;
    }

    try {
      await createUserWithEmailAndPassword(auth, email, password);
      navigate('/main');
    } catch (error: any) {
      if (error.code === 'auth/email-already-in-use') {
        setErrorMessage('Email already exists with an account');
      } else {
        setErrorMessage(error.message);
      }
    }
  };

  return (
    <div className="login-box">
      <div className="login-bar">
        <div onClick={() => switchMode(false)} className={!isLoginMode ? 'active' : ''}>Sign Up</div>
        <div onClick={() => switchMode(true)} className={isLoginMode ? 'active' : ''}>Login</div>
      </div>

      {isLoginMode ? (
        <form onSubmit={login}>
          <p className="login-info">Enter your email address</p>
          <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" autoComplete="off" required />
          <p className="login-info">Enter your password</p>
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" autoComplete="off" required minLength={6} />
          <button type="submit" className="login-button" disabled={!email || password.length < 6}>Login</button>
          {errorMessage && <p className="login-error">{errorMessage}</p>}
        </form>
      ) : (
        <form onSubmit={signup}>
          <p className="login-info">Please put a valid email address</p>
          <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" autoComplete="off" required />
          <span className="login-info">Create a password </span>
          <span className="login-requirements">(*Must be at least 6 characters long)</span>
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" autoComplete="off" required minLength={6} />
          <input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Confirm Password" autoComplete="off" required minLength={6} />
          <button type="submit" className="login-button" disabled={!email || password.length < 6 || confirmPassword.length < 6}>Sign Up</button>
          {errorMessage && <p className="login-error">{errorMessage}</p>}
        </form>
      )}
    </div>
  );
}

// src/app/login/login-signup/login-signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { AngularFireAuth } from '@angular/fire/compat/auth';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login-signup',
  templateUrl: './login-signup.component.html',
  styleUrls: ['./login-signup.component.css']
})
export class LoginSignupComponent implements OnInit {
  isLoginMode = true;
  errorMessage: string = '';

  loginForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  });

  signupForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
    confirmPassword: ['', [Validators.required, Validators.minLength(6)]]
  });

  constructor(
    private fb: FormBuilder, 
    private afAuth: AngularFireAuth, 
    private router: Router,
    private authService: AuthService
  ) {}

  ngOnInit(): void {}

  switchMode(isLoginMode: boolean) {
    this.isLoginMode = isLoginMode;
    this.errorMessage = '';
  }

  async login() {
    if (this.loginForm.invalid) {
      return;
    }

    const { email, password } = this.loginForm.value;

    try {
      await this.afAuth.signInWithEmailAndPassword(email ?? '', password ?? '');
      if (email && password) {
        this.authService.updateUserCredentials(email, password);
      }
      this.router.navigate(['/main']); 
    } catch (error: any) {
      if (error.code === 'auth/wrong-password' || error.code === 'auth/user-not-found') {
        this.errorMessage = 'Incorrect username or password';
      } else {
        this.errorMessage = error.message;
      }
    }
  }

  async signup() {
    if (this.signupForm.invalid) {
      return;
    }

    const { email, password, confirmPassword } = this.signupForm.value;

    if (password !== confirmPassword) {
      this.errorMessage = 'Passwords do not match';
      return;
    }

    try {
      await this.afAuth.createUserWithEmailAndPassword(email ?? '', password ?? '');
      if (email && password) {
        this.authService.updateUserCredentials(email, password);
      }
      this.router.navigate(['/main']);
    } catch (error: any) {
      if (error.code === 'auth/email-already-in-use') {
        this.errorMessage = 'Email already exists with an account';
      } else {
        this.errorMessage = error.message;
      }
    }
  }
}

<div class="box">
  <div class="bar">
    <div (click)="switchMode(false)" [class.active]="!isLoginMode">Sign Up</div>
    <div (click)="switchMode(true)" [class.active]="isLoginMode">Login</div>
  </div>

  <div *ngIf="isLoginMode; else signupFormTemplate">
    <form [formGroup]="loginForm" (ngSubmit)="login()">
      <p class="info">Enter your email address</p>
      <input type="email" formControlName="email" placeholder="Email" autocomplete="off">
      <p class="info">Enter your password</p>
      <input type="password" formControlName="password" placeholder="Password" autocomplete="off">
      <button type="submit" class="button" [disabled]="loginForm.invalid">Login</button>
      <p *ngIf="errorMessage" class="error">{{ errorMessage }}</p>
    </form>
  </div>

  <ng-template #signupFormTemplate>
    <form [formGroup]="signupForm" (ngSubmit)="signup()">
      <p class="info">Please put a valid email address</p>
      <input type="email" formControlName="email" placeholder="Email" autocomplete="off">
      <span class="info">Create a password </span>
      <span class="requirements">(*Must be at least 6 characters long)</span>
      <input type="password" formControlName="password" placeholder="Password" autocomplete="off">
      <input type="password" formControlName="confirmPassword" placeholder="Confirm Password" autocomplete="off">
      <button type="submit" class="button" [disabled]="signupForm.invalid">Sign Up</button>
      <p *ngIf="errorMessage" class="error">{{ errorMessage }}</p>
    </form>
  </ng-template>
</div>
