// src/components/rice-alcohol/RiceAlcoholBrands.tsx
import './RiceAlcoholBrands.css';

export default function RiceAlcoholBrands() {
  return (
    <div className="rice-alcohol-brands-container">
        <p className="rice-alcohol-brands-title">Rice Elixirs of Excellence (The Star Brands):</p>
        <div className="rice-alcohol-brands-content">
            <p className="title-sakeone">SAKEONE (MOMOKAWA)</p>
            <p className="content-sakeone">Based in the United States, SakeOne is a beacon of sake production outside of Japan. Their Momokawa brand is a testament to the art of sake brewing, offering a range of premium sake varieties that have garnered international acclaim. Their dedication to authenticity and quality has made them a favorite among sake enthusiasts worldwide.</p><br/>
                
            <p className="title-hitejinro">HITEJINRO</p>
            <p className="content-hitejinro">Originating from South Korea, HiteJinro is a brand that has become synonymous with soju, a clear spirit distilled from rice and other grains. Their "Chamisul" soju is not just popular in Korea but has made waves internationally. Beyond its smooth taste, the brand represents the rich drinking culture of Korea, where soju is often enjoyed with meals and celebrations.</p><br/>
        
            <p className="title-ninki">NINKI INC.</p>
            <p className="content-ninki">Hailing from Japan, Ninki Inc. is a revered sake brewery known for its craft sake. Their Ninki-Ichi brand, in particular, stands out for its meticulous brewing process and the depth of flavors it offers. Each bottle encapsulates the rich tradition of Japanese sake brewing, making it a favorite among connoisseurs.</p><br/>

            <p className="title-shochikubai">SHO CHIKU BAI (TAKARA SAKE USA)</p>
            <p className="content-shochikubai">Takara Sake USA, with its Sho Chiku Bai brand, has brought the essence of Japanese sake to the shores of the United States. Recognized for its authentic taste and brewing techniques, Sho Chiku Bai is a celebration of both tradition and innovation. It's a brand that has bridged cultures and introduced many to the nuanced world of sake.</p><br/>

            <p className="closing">In the realm of rice-based alcohols, these brands stand tall, each narrating a unique story of tradition, culture, and craftsmanship. They're not just drinks; they're a journey through history and flavors. So, the next time you savor one of these, take a moment to appreciate the legacy and artistry in every sip. Cheers to the maestros of the malted rice! 🍶🌏🌟</p>
        </div>
    </div>
  );
}

// src/app/rice-alcohol/rice-alcohol-brands/rice-alcohol-brands.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-brands',
  templateUrl: './rice-alcohol-brands.component.html',
  styleUrls: ['./rice-alcohol-brands.component.css']
})
export class RiceAlcoholBrandsComponent {

}

<div class="container">
    <p class="title">Rice Elixirs of Excellence (The Star Brands):</p>
    <div class="content">
        <p class="title-sakeone">SAKEONE (MOMOKAWA)</p>
        <p class="content-sakeone">Based in the United States, SakeOne is a beacon of sake production outside of Japan. Their Momokawa brand is a testament to the art of sake brewing, offering a range of premium sake varieties that have garnered international acclaim. Their dedication to authenticity and quality has made them a favorite among sake enthusiasts worldwide.</p><br>
            
        <p class="title-hitejinro">HITEJINRO</p>
        <p class="content-hitejinro">Originating from South Korea, HiteJinro is a brand that has become synonymous with soju, a clear spirit distilled from rice and other grains. Their "Chamisul" soju is not just popular in Korea but has made waves internationally. Beyond its smooth taste, the brand represents the rich drinking culture of Korea, where soju is often enjoyed with meals and celebrations.</p><br>
    
        <p class="title-ninki">NINKI INC.</p>
        <p class="content-ninki">Hailing from Japan, Ninki Inc. is a revered sake brewery known for its craft sake. Their Ninki-Ichi brand, in particular, stands out for its meticulous brewing process and the depth of flavors it offers. Each bottle encapsulates the rich tradition of Japanese sake brewing, making it a favorite among connoisseurs.</p><br>

        <p class="title-shochikubai">SHO CHIKU BAI (TAKARA SAKE USA)</p>
        <p class="content-shochikubai">Takara Sake USA, with its Sho Chiku Bai brand, has brought the essence of Japanese sake to the shores of the United States. Recognized for its authentic taste and brewing techniques, Sho Chiku Bai is a celebration of both tradition and innovation. It's a brand that has bridged cultures and introduced many to the nuanced world of sake.</p><br>

        <p class="closing">In the realm of rice-based alcohols, these brands stand tall, each narrating a unique story of tradition, culture, and craftsmanship. They're not just drinks; they're a journey through history and flavors. So, the next time you savor one of these, take a moment to appreciate the legacy and artistry in every sip. Cheers to the maestros of the malted rice! 🍶🌏🌟</p>
    </div>
</div>
