// src/components/wine/WineTypes.tsx
import './WineTypes.css';

export default function WineTypes() {
  return (
    <div className="wine-types-container">
        <p className="wine-types-title">Dive into the Enchanting World of Wines:</p>
        <div className="wine-types-content">

            <p className="title-red">RED WINE</p>
            <p className="content-red">Red wine, often described as the passionate poet of the wine world, paints tales of romance, candlelit dinners, and whispered secrets under a canopy of stars. Its spectrum of colors, from intense violet to brick red, tells stories of dark-colored grape varieties and the magic of fermentation with grape skins. Places like Bordeaux and Tuscany are not just regions; they're legends, crafting some of the world's most cherished reds. Whether you're sipping the bold Cabernet Sauvignon or the delicate Pinot Noir, with red wine, every glass is a narrative.</p><br/>

            <p className="title-white">WHITE WINE</p>
            <p className="content-white">White wine dances gracefully through the wine spectrum. It's the zephyr on a balmy day, often teasing with hints of citrus, apple, or floral notes. Made predominantly from green or yellow grapes, its clarity comes from fermenting without the grape skins. Regions like Burgundy and parts of California are like artists, painting flavors with every bottle. From the oaky Chardonnay to the crisp Sauvignon Blanc, white wines are a refreshing melody of flavors.</p><br/>

            <p className="title-rose">ROSÉ</p>
            <p className="content-rose">Rosé is the daydreamer, capturing the essence of golden sunsets, blooming roses, and memories of youth. It's the middle child, borrowing the best from reds and whites. Its pinkish charm comes from a fleeting romance with grape skins. Provence in France is its most famous home, but rosé travels the world, bringing with it a sip of summer, hints of red fruit, citrus, and sometimes a touch of spice. It's the wine that whispers of picnics and beachside toasts.</p><br/>

            <p className="title-sparkling">SPARKLING WINE</p>
            <p className="content-sparkling">Sparkling wine is the life of the party! It's the pop of a cork, the cascade of bubbles, and the sparkle in one's eye. While Champagne is the crown jewel, regions from Italy's Prosecco to Spain's Cava add their own effervescent touch. The magic lies in its secondary fermentation, which gifts it those delightful bubbles. It's not just a drink; it's an emotion, a celebration, a toast to the now!</p><br/>

            <p className="title-dessert">DESSERT WINE</p>
            <p className="content-dessert">Dessert wine is the sweet serenade concluding a meal. It's the golden hues of late harvests, the richness of noble rot, and the luxury of patience. Think of the honeyed Sauternes, the luscious Ice Wines, or the sun-drenched Tokaji. These wines are nature's dessert, offering a symphony of sweetness, balanced with acidity, and a dance of flavors on the palate.</p><br/>

            <p className="title-fortified">FORTIFIED WINE</p>
            <p className="content-fortified">Fortified wine is the bold storyteller, narrating tales of voyages and adventures. With a splash of spirits, usually brandy, it's intense, warming, and complex. From the nutty notes of Sherry, the rich layers of Port, to the caramel hints of Madeira, every sip is a journey. It's the wine of sailors, explorers, and those who dare to venture beyond the horizon.</p><br/>

            <p className="closing">From the sun-kissed vineyards of Tuscany to the misty valleys of California, wines are a tapestry of stories, flavors, and memories. So, here's to the vintners, the grapes, and to us, the fortunate explorers of this delightful world! 🍷</p>
        </div>
    </div>
  );
}

// src/app/wine/wine-types/wine-types.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-types',
  templateUrl: './wine-types.component.html',
  styleUrls: ['./wine-types.component.css']
})
export class WineTypesComponent {

}

<div class="container">
    <p class="title">Dive into the Enchanting World of Wines:</p>
    <div class="content">

        <p class="title-red">RED WINE</p>
        <p class="content-red">Red wine, often described as the passionate poet of the wine world, paints tales of romance, candlelit dinners, and whispered secrets under a canopy of stars. Its spectrum of colors, from intense violet to brick red, tells stories of dark-colored grape varieties and the magic of fermentation with grape skins. Places like Bordeaux and Tuscany are not just regions; they're legends, crafting some of the world's most cherished reds. Whether you're sipping the bold Cabernet Sauvignon or the delicate Pinot Noir, with red wine, every glass is a narrative.</p><br>

        <p class="title-white">WHITE WINE</p>
        <p class="content-white">White wine dances gracefully through the wine spectrum. It's the zephyr on a balmy day, often teasing with hints of citrus, apple, or floral notes. Made predominantly from green or yellow grapes, its clarity comes from fermenting without the grape skins. Regions like Burgundy and parts of California are like artists, painting flavors with every bottle. From the oaky Chardonnay to the crisp Sauvignon Blanc, white wines are a refreshing melody of flavors.</p><br>

        <p class="title-rose">ROSÉ</p>
        <p class="content-rose">Rosé is the daydreamer, capturing the essence of golden sunsets, blooming roses, and memories of youth. It's the middle child, borrowing the best from reds and whites. Its pinkish charm comes from a fleeting romance with grape skins. Provence in France is its most famous home, but rosé travels the world, bringing with it a sip of summer, hints of red fruit, citrus, and sometimes a touch of spice. It's the wine that whispers of picnics and beachside toasts.</p><br>

        <p class="title-sparkling">SPARKLING WINE</p>
        <p class="content-sparkling">Sparkling wine is the life of the party! It's the pop of a cork, the cascade of bubbles, and the sparkle in one's eye. While Champagne is the crown jewel, regions from Italy's Prosecco to Spain's Cava add their own effervescent touch. The magic lies in its secondary fermentation, which gifts it those delightful bubbles. It's not just a drink; it's an emotion, a celebration, a toast to the now!</p><br>

        <p class="title-dessert">DESSERT WINE</p>
        <p class="content-dessert">Dessert wine is the sweet serenade concluding a meal. It's the golden hues of late harvests, the richness of noble rot, and the luxury of patience. Think of the honeyed Sauternes, the luscious Ice Wines, or the sun-drenched Tokaji. These wines are nature's dessert, offering a symphony of sweetness, balanced with acidity, and a dance of flavors on the palate.</p><br>

        <p class="title-fortified">FORTIFIED WINE</p>
        <p class="content-fortified">Fortified wine is the bold storyteller, narrating tales of voyages and adventures. With a splash of spirits, usually brandy, it's intense, warming, and complex. From the nutty notes of Sherry, the rich layers of Port, to the caramel hints of Madeira, every sip is a journey. It's the wine of sailors, explorers, and those who dare to venture beyond the horizon.</p><br>

        <p class="closing">From the sun-kissed vineyards of Tuscany to the misty valleys of California, wines are a tapestry of stories, flavors, and memories. So, here's to the vintners, the grapes, and to us, the fortunate explorers of this delightful world! 🍷</p>
    </div>
</div>
