// src/components/rice-alcohol/RiceAlcoholTypes.tsx
import './RiceAlcoholTypes.css';

export default function RiceAlcoholTypes() {
  return (
    <div className="rice-alcohol-types-container">
        <p className="rice-alcohol-types-title">The Rice Alcohol Chronicles:</p>
        <div className="rice-alcohol-types-content">
            <p className="title-sake">SAKE</p>
            <p className="content-sake">Japan's elegant elixir, Sake, is a dance of rice grains in a glass. Crafted with special sake rice, koji mold, and pristine waters, its taste can be fruity, floral, or even umami-rich. The polishing rate of the rice grains can influence its flavor, leading to variations like Junmai, Ginjo, and Daiginjo. Sake's versatility is its charm, with some variants offering notes of apple, melon, or even caramel.</p><br/>
                
            <p className="title-soju">SOJU</p>
            <p className="content-soju">Korea's spirited sensation, Soju, is a blend of grains and starches. Modern Soju, made from sweet potatoes or tapioca, can have a slightly sweeter profile, while traditional versions offer a cleaner, sharper taste. The distillation process gives Soju its signature kick, with flavors ranging from neutral to slightly sweet, often with a hint of botanicals.</p><br/>
        
            <p className="title-mijiu">MIJIU</p>
            <p className="content-mijiu">China's Mijiu, with its base of glutinous rice and yeast balls, can range from sweet to semi-sweet. The fermentation duration and ingredients like osmanthus flowers or rose petals can introduce delightful aromatic notes, making Mijiu a fragrant journey through Chinese traditions.</p><br/>

            <p className="title-ruou-can">RƯỢU CẦN</p>
            <p className="content-ruou-can">Vietnam's Rượu cần, made from glutinous rice and special yeast, offers a mildly sweet and aromatic profile. Some variants might include additional ingredients like fruits or herbs, introducing subtle flavors that dance on the palate, reminiscent of Vietnam's diverse landscapes.</p><br/>

            <p className="title-lao-lao">LAO-LAO</p>
            <p className="content-lao-lao">Lao-Lao, with its base of sticky rice and natural yeast, has a robust and earthy flavor. The charred wood storage imparts a smoky undertone, making it a bold drink that captures the essence of Laos' rugged terrains and rich traditions.</p><br/>

            <p className="title-tapuy">TAPUY</p>
            <p className="content-tapuy">The Philippines' Tapuy, brewed from heirloom rice varieties and local fermentation agents, has a mildly sweet and tangy profile. The fermentation process, often aided by wild yeasts, gives Tapuy its distinct taste, echoing the archipelago's vibrant culture and traditions.</p><br/>
            
            <p className="closing">From the serene landscapes of Japan to the rhythmic beats of Korea, and from the vast terrains of China to the communal gatherings of Vietnam, rice-based alcohols are a journey through cultures, traditions, and flavors. Each drink, with its unique ingredients and taste profiles, tells a story of its homeland. So, here's to the tales told by grains, to the symphonies of fermentation, and to the world of rice alcohols that never ceases to amaze! 🍶</p>
        </div>
    </div>
  );
}

// src/app/rice-alcohol/rice-alcohol-types/rice-alcohol-types.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-rice-alcohol-types',
  templateUrl: './rice-alcohol-types.component.html',
  styleUrls: ['./rice-alcohol-types.component.css']
})
export class RiceAlcoholTypesComponent {

}

<div class="container">
    <p class="title">The Rice Alcohol Chronicles:</p>
    <div class="content">
        <p class="title-sake">SAKE</p>
        <p class="content-sake">Japan's elegant elixir, Sake, is a dance of rice grains in a glass. Crafted with special sake rice, koji mold, and pristine waters, its taste can be fruity, floral, or even umami-rich. The polishing rate of the rice grains can influence its flavor, leading to variations like Junmai, Ginjo, and Daiginjo. Sake's versatility is its charm, with some variants offering notes of apple, melon, or even caramel.</p><br>
            
        <p class="title-soju">SOJU</p>
        <p class="content-soju">Korea's spirited sensation, Soju, is a blend of grains and starches. Modern Soju, made from sweet potatoes or tapioca, can have a slightly sweeter profile, while traditional versions offer a cleaner, sharper taste. The distillation process gives Soju its signature kick, with flavors ranging from neutral to slightly sweet, often with a hint of botanicals.</p><br>
    
        <p class="title-mijiu">MIJIU</p>
        <p class="content-mijiu">China's Mijiu, with its base of glutinous rice and yeast balls, can range from sweet to semi-sweet. The fermentation duration and ingredients like osmanthus flowers or rose petals can introduce delightful aromatic notes, making Mijiu a fragrant journey through Chinese traditions.</p><br>

        <p class="title-ruou-can">RƯỢU CẦN</p>
        <p class="content-ruou-can">Vietnam's Rượu cần, made from glutinous rice and special yeast, offers a mildly sweet and aromatic profile. Some variants might include additional ingredients like fruits or herbs, introducing subtle flavors that dance on the palate, reminiscent of Vietnam's diverse landscapes.</p><br>

        <p class="title-lao-lao">LAO-LAO</p>
        <p class="content-lao-lao">Lao-Lao, with its base of sticky rice and natural yeast, has a robust and earthy flavor. The charred wood storage imparts a smoky undertone, making it a bold drink that captures the essence of Laos' rugged terrains and rich traditions.</p><br>

        <p class="title-tapuy">TAPUY</p>
        <p class="content-tapuy">The Philippines' Tapuy, brewed from heirloom rice varieties and local fermentation agents, has a mildly sweet and tangy profile. The fermentation process, often aided by wild yeasts, gives Tapuy its distinct taste, echoing the archipelago's vibrant culture and traditions.</p><br>
        
        <p class="closing">From the serene landscapes of Japan to the rhythmic beats of Korea, and from the vast terrains of China to the communal gatherings of Vietnam, rice-based alcohols are a journey through cultures, traditions, and flavors. Each drink, with its unique ingredients and taste profiles, tells a story of its homeland. So, here's to the tales told by grains, to the symphonies of fermentation, and to the world of rice alcohols that never ceases to amaze! 🍶</p>
    </div>
</div>
