// src/app/search/search-bar/search-bar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.css']
})
export class SearchBarComponent {
  searchTerm: string = '';

  @Output() searchChanged: EventEmitter<string> = new EventEmitter();

  onInputChange() {
    this.searchChanged.emit(this.searchTerm);
  }
  
  clearSearch() {
    this.searchTerm = '';
    this.onInputChange();
  }
  
}

<div class="search-container">
    <input [(ngModel)]="searchTerm" (input)="onInputChange()" placeholder="Search...">
    <button *ngIf="searchTerm" class="clear-btn" (click)="clearSearch()">x</button>
  </div>

// src/components/search/SearchBar.tsx
import type { ChangeEvent } from 'react';
import './SearchBar.css';

interface SearchBarProps {
  searchTerm: string;
  onSearchChange: (term: string) => void;
}

export default function SearchBar({ searchTerm, onSearchChange }: SearchBarProps) {
  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    onSearchChange(e.target.value);
  };

  const clearSearch = () => {
    onSearchChange('');
  };

  return (
    <div className="search-container">
        <input 
          value={searchTerm} 
          onChange={handleInputChange} 
          placeholder="Search..."
        />
        {searchTerm && (
          <button className="clear-btn" onClick={clearSearch}>x</button>
        )}
    </div>
  );
}
