// src/components/about/AboutTitle.tsx
import './AboutTitle.css';

export default function AboutTitle() {
  return (
    <div className="about-title-container">
        <img src="/assets/images/about-images/cheers.jpg" alt="cheers image" className="title-image" />
        <div className="content">
            <p className="title">ABOUT US</p>
            <p className="h2">From Barrel to Bottle: Discover the Magic Within.</p>
        </div>
    </div>
  );
}

// src/app/about/about-title/about-title.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about-title',
  templateUrl: './about-title.component.html',
  styleUrls: ['./about-title.component.css']
})
export class AboutTitleComponent {

}

<div class="container">
    <img src="assets/images/about-images/cheers.jpg" alt="cheers image" class="title-image">
    <div class="content">
        <p class="title">ABOUT US</p>
        <p class="h2">From Barrel to Bottle: Discover the Magic Within.</p>
    </div>
</div>
