// src/components/spirit/SpiritBrands.tsx
import './SpiritBrands.css';

export default function SpiritBrands() {
  return (
    <div className="spirit-brands-container">
        <p className="spirit-brands-title">World's Spirit Titans (The Top Producers):</p>
        <div className="spirit-brands-content">

            <p className="title-diageo">DIAGEO</p>
            <p className="content-diageo">Hailing from the UK, Diageo stands tall as a global leader in the spirits world. With iconic brands like Johnnie Walker, Smirnoff, and Baileys under its belt, they've mastered the art of crafting spirits that resonate with every palate. From the smoky trails of Scotch whisky to the creamy allure of Baileys, Diageo brings a world of flavors to our glasses. Cheers to their spirited journey!</p><br/>

            <p className="title-pernod">PERNOD RICARD</p>
            <p className="content-pernod">From the romantic streets of France, Pernod Ricard emerges as a connoisseur of fine spirits. With a portfolio boasting Absolut Vodka's clarity and Jameson Irish Whiskey's warmth, they've painted a global canvas of flavors. Dive into a world where every sip tells a story of tradition, innovation, and French flair. Santé!</p><br/>

            <p className="title-beam">BEAM SUNTORY</p>
            <p className="content-beam">A fusion of American spirit and Japanese precision, Beam Suntory offers a symphony of flavors. Whether it's the boldness of Jim Beam, the craftsmanship of Maker's Mark, or the elegance of Yamazaki, they've got a note for every taste. A toast to the East meets West in every bottle!</p><br/>

            <p className="title-bacardi">BACARDI LIMITED</p>
            <p className="content-bacardi">Starting its journey amidst Cuba's vibrant rhythms, Bacardi now dances on the global stage. With its signature rum, the smoothness of Grey Goose vodka, and the botanical magic of Bombay Sapphire gin, Bacardi brings the party to life. Let's sway to the beats of Bacardi's spirited legacy!</p><br/>

            <p className="title-brown">BROWN-FORMAN CORPORATION</p>
            <p className="content-brown">Straight from America's heartland, Brown-Forman is a tale of passion and craftsmanship. With Jack Daniel's smoky embrace and Woodford Reserve's refined taste, they've crafted legends. Dive into a world where every drop is a testament to dedication and love for the craft. Yeehaw!</p><br/>

            <p className="title-lvmh">LVMH (Moët Hennessy Louis Vuitton)</p>
            <p className="content-lvmh">Beyond the glitz of luxury fashion, LVMH dazzles in the spirits realm. From the sophisticated bubbles of Moët & Chandon to the rich heritage of Hennessy, they offer a sip of luxury. Embark on a journey where every glass is a celebration of elegance and style. À votre santé!</p><br/>

            <p className="closing">From the heart of distilleries to our glasses, these spirit giants have woven tales of passion, innovation, and legacy. As we raise our glasses, let's celebrate the maestros who've turned simple ingredients into liquid gold. Here's to the legends of the spirits world! 🥃🍸🌍</p>
        </div>
    </div>
  );
}

// src/app/spirit/spirit-brands/spirit-brands.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-spirit-brands',
  templateUrl: './spirit-brands.component.html',
  styleUrls: ['./spirit-brands.component.css']
})
export class SpiritBrandsComponent {

}

<div class="container">
    <p class="title">World's Spirit Titans (The Top Producers):</p>
    <div class="content">

        <p class="title-diageo">DIAGEO</p>
        <p class="content-diageo">Hailing from the UK, Diageo stands tall as a global leader in the spirits world. With iconic brands like Johnnie Walker, Smirnoff, and Baileys under its belt, they've mastered the art of crafting spirits that resonate with every palate. From the smoky trails of Scotch whisky to the creamy allure of Baileys, Diageo brings a world of flavors to our glasses. Cheers to their spirited journey!</p><br>

        <p class="title-pernod">PERNOD RICARD</p>
        <p class="content-pernod">From the romantic streets of France, Pernod Ricard emerges as a connoisseur of fine spirits. With a portfolio boasting Absolut Vodka's clarity and Jameson Irish Whiskey's warmth, they've painted a global canvas of flavors. Dive into a world where every sip tells a story of tradition, innovation, and French flair. Santé!</p><br>

        <p class="title-beam">BEAM SUNTORY</p>
        <p class="content-beam">A fusion of American spirit and Japanese precision, Beam Suntory offers a symphony of flavors. Whether it's the boldness of Jim Beam, the craftsmanship of Maker's Mark, or the elegance of Yamazaki, they've got a note for every taste. A toast to the East meets West in every bottle!</p><br>

        <p class="title-bacardi">BACARDI LIMITED</p>
        <p class="content-bacardi">Starting its journey amidst Cuba's vibrant rhythms, Bacardi now dances on the global stage. With its signature rum, the smoothness of Grey Goose vodka, and the botanical magic of Bombay Sapphire gin, Bacardi brings the party to life. Let's sway to the beats of Bacardi's spirited legacy!</p><br>

        <p class="title-brown">BROWN-FORMAN CORPORATION</p>
        <p class="content-brown">Straight from America's heartland, Brown-Forman is a tale of passion and craftsmanship. With Jack Daniel's smoky embrace and Woodford Reserve's refined taste, they've crafted legends. Dive into a world where every drop is a testament to dedication and love for the craft. Yeehaw!</p><br>

        <p class="title-lvmh">LVMH (Moët Hennessy Louis Vuitton)</p>
        <p class="content-lvmh">Beyond the glitz of luxury fashion, LVMH dazzles in the spirits realm. From the sophisticated bubbles of Moët & Chandon to the rich heritage of Hennessy, they offer a sip of luxury. Embark on a journey where every glass is a celebration of elegance and style. À votre santé!</p><br>

        <p class="closing">From the heart of distilleries to our glasses, these spirit giants have woven tales of passion, innovation, and legacy. As we raise our glasses, let's celebrate the maestros who've turned simple ingredients into liquid gold. Here's to the legends of the spirits world! 🥃🍸🌍</p>
    </div>
</div>
