// src/components/beer/BeerOverview.tsx
import './BeerOverview.css';

export default function BeerOverview() {
  return (
    <div className="beer-overview-container">
        <p className="beer-overview-title">The Great Beer Saga:</p>
        <p className="beer-overview-content">Once upon a time, in a universe not so different from ours, there was a pressing question: "What on Earth do we drink when the water's looking a tad suspicious?" And thus, beer was born as the universe's bubbly solution!<br/>
            <br/>   
            Now, let's talk about this magical potion. It wasn't just any brew; it was a masterful concoction. Grains, once dreaming of becoming the next breakfast cereal sensation, decided to pivot. They thought, "Why not dive into the world of beverages?" And so, they gave up their cereal dreams to become the heart of this delightful drink.<br/>
            <br/>            
            But the grains weren't alone on this journey. They were joined by water, the essence of life, and hops, those green little wonders that always aspired to add a burst of flavor to anything they touched. And let's not forget yeast – the unsung heroes of the beverage world. Working tirelessly, they fermented this mixture to sheer perfection, making sure every sip was a dance of flavors.<br/>
            <br/>            
            From continent to continent, this brew spread, bringing joy, laughter, and a few memorable nights. And that, dear reader, is the tale of beer, the drink that conquered the world with its taste and charm.
        </p>
    </div>
  );
}

// src/app/beer/beer-overview/beer-overview.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-beer-overview',
  templateUrl: './beer-overview.component.html',
  styleUrls: ['./beer-overview.component.css']
})
export class BeerOverviewComponent {

}

<div class="container">
        <p class="title">The Great Beer Saga:</p>
        <p class="content">Once upon a time, in a universe not so different from ours, there was a pressing question: "What on Earth do we drink when the water's looking a tad suspicious?" And thus, beer was born as the universe's bubbly solution!<br>
            <br>   
            Now, let's talk about this magical potion. It wasn't just any brew; it was a masterful concoction. Grains, once dreaming of becoming the next breakfast cereal sensation, decided to pivot. They thought, "Why not dive into the world of beverages?" And so, they gave up their cereal dreams to become the heart of this delightful drink.<br>
            <br>            
            But the grains weren't alone on this journey. They were joined by water, the essence of life, and hops, those green little wonders that always aspired to add a burst of flavor to anything they touched. And let's not forget yeast – the unsung heroes of the beverage world. Working tirelessly, they fermented this mixture to sheer perfection, making sure every sip was a dance of flavors.<br>
            <br>            
            From continent to continent, this brew spread, bringing joy, laughter, and a few memorable nights. And that, dear reader, is the tale of beer, the drink that conquered the world with its taste and charm.
        </p>
</div>
