// src/components/wine/WineHistory.tsx
import './WineHistory.css';

export default function WineHistory() {
  return (
    <div className="wine-history-container">
        <p className="wine-history-title">
            A Vintage Voyage Through Vines</p>
        <div className="wine-history-content">
            <p className="p1">
                The tale of wine begins around 6,000 BC in the Caucasus region, where the first grapevines were believed to be domesticated. Ancient civilizations soon discovered that fermenting crushed grapes resulted in a delightful beverage. This discovery spread rapidly, with evidence of early winemaking found in ancient China, Persia, and Egypt. The Egyptians, in particular, considered wine a drink of the elite, often reserved for religious ceremonies and buried with pharaohs to accompany them in the afterlife.
            <br/><br/></p>
            <p className="p2">
                The Greeks and Romans played pivotal roles in the spread and sophistication of viticulture. For the Greeks, wine was a daily beverage, and they worshipped Dionysus, the god of wine. They also pioneered the concept of "terroir," recognizing that different regions produced distinct wine flavors. The Romans, with their vast empire, spread viticulture across Europe. They improved cultivation techniques, introduced wooden barrels for aging, and even penned detailed winemaking manuals.
                <br/><br/></p>
            <p className="p3">
                During the Middle Ages, the Christian Church became the guardian of winemaking, with monasteries refining the art and science of viticulture. Monks meticulously documented their methods, leading to consistent and improved wine quality. The Renaissance period saw the rise of dedicated wineries, and regions like Bordeaux in France began to gain recognition for their exceptional wines.
                <br/><br/></p>
            <p className="p4">
                The 19th century brought both innovation and calamity to the wine world. The invention of the wine bottle and cork allowed wines to age and develop complexity. However, the European vineyards faced devastation from the phylloxera pest. Salvation came in the form of American vines, which were resistant to the pest and used as rootstocks. This period also saw the emergence of wine classifications, with regions like Bordeaux ranking their wines based on quality.
                <br/><br/></p>
            <p className="p5">
                Today, wine is celebrated globally, with regions from France to Australia and Chile to South Africa producing stellar vintages. The modern era has embraced both tradition and technology, with winemakers experimenting with hybrid grapes and sustainable practices. Wine festivals, tastings, and sommelier courses reflect the world's enduring love affair with wine. From its ancient origins to today's innovative wineries, wine's journey is a testament to humanity's passion for this exquisite drink. So, raise a glass to wine – a beverage rich in history, flavor, and elegance!
                <br/><br/></p>
        </div>
    </div>
  );
}

// src/app/wine/wine-history/wine-history.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-wine-history',
  templateUrl: './wine-history.component.html',
  styleUrls: ['./wine-history.component.css']
})
export class WineHistoryComponent {

}

<div class="container">
    <p class="title">
        A Vintage Voyage Through Vines</p>
    <div class="content">
        <p class="p1">
            The tale of wine begins around 6,000 BC in the Caucasus region, where the first grapevines were believed to be domesticated. Ancient civilizations soon discovered that fermenting crushed grapes resulted in a delightful beverage. This discovery spread rapidly, with evidence of early winemaking found in ancient China, Persia, and Egypt. The Egyptians, in particular, considered wine a drink of the elite, often reserved for religious ceremonies and buried with pharaohs to accompany them in the afterlife.
        <br><br></p>
        <p class="p2">
            The Greeks and Romans played pivotal roles in the spread and sophistication of viticulture. For the Greeks, wine was a daily beverage, and they worshipped Dionysus, the god of wine. They also pioneered the concept of "terroir," recognizing that different regions produced distinct wine flavors. The Romans, with their vast empire, spread viticulture across Europe. They improved cultivation techniques, introduced wooden barrels for aging, and even penned detailed winemaking manuals.
            <br><br></p>
        <p class="p3">
            During the Middle Ages, the Christian Church became the guardian of winemaking, with monasteries refining the art and science of viticulture. Monks meticulously documented their methods, leading to consistent and improved wine quality. The Renaissance period saw the rise of dedicated wineries, and regions like Bordeaux in France began to gain recognition for their exceptional wines.
            <br><br></p>
        <p class="p4">
            The 19th century brought both innovation and calamity to the wine world. The invention of the wine bottle and cork allowed wines to age and develop complexity. However, the European vineyards faced devastation from the phylloxera pest. Salvation came in the form of American vines, which were resistant to the pest and used as rootstocks. This period also saw the emergence of wine classifications, with regions like Bordeaux ranking their wines based on quality.
            <br><br></p>
        <p class="p5">
            Today, wine is celebrated globally, with regions from France to Australia and Chile to South Africa producing stellar vintages. The modern era has embraced both tradition and technology, with winemakers experimenting with hybrid grapes and sustainable practices. Wine festivals, tastings, and sommelier courses reflect the world's enduring love affair with wine. From its ancient origins to today's innovative wineries, wine's journey is a testament to humanity's passion for this exquisite drink. So, raise a glass to wine – a beverage rich in history, flavor, and elegance!
            <br><br></p>
    </div>
</div>
