// src/app/global/header/header.component.ts
import { Component, OnDestroy } from '@angular/core';
import { ViewportScroller } from '@angular/common';
import { AuthService } from '../../services/auth.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnDestroy {
  isLoggedIn = false;
  userEmail: string | null = null;
  userPassword: string | null = null; // Add this line
  private subscription: Subscription;

  constructor(
    private viewportScroller: ViewportScroller,
    private authService: AuthService // Inject the AuthService
  ) {
    // Subscribe to userCredentials$ observable from AuthService
    this.subscription = this.authService.userCredentials$.subscribe(credentials => {
      if (credentials) {
        this.userEmail = credentials.email;
        this.userPassword = credentials.password; // Update password from the credentials
        this.isLoggedIn = !!this.userEmail; // Update isLoggedIn based on whether email is present
      } else {
        this.userEmail = null;
        this.userPassword = null;
        this.isLoggedIn = false;
      }
    });
  }

  onLinkClick() {
    this.viewportScroller.scrollToPosition([0, 0]);
  }

  handleLogin(): void {
    this.isLoggedIn = true;
    console.log('Logged in:', this.isLoggedIn);
  }
  
  handleLogout(): void {
    this.isLoggedIn = false;
    console.log('Logged out:', this.isLoggedIn);
  }

  // Implement OnDestroy to unsubscribe from observables
  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }
}

<div class="header" id="myheader">
    <div class="logo-title-container">
        <a [routerLink]="['/main']" (click)="onLinkClick()">
            <h1 class="title">ALHOCOOL</h1>
        </a>
    </div>
    <nav class="nav-links">
        <div class="explore-dropdown">
            <button class="explore-button" disabled>EXPLORE</button>
            <div class="dropdown-content">
                <a [routerLink]="['/beer']" (click)="onLinkClick()">Beers</a>
                <a [routerLink]="['/wine']" (click)="onLinkClick()">Wines</a>
                <a [routerLink]="['/spirit']" (click)="onLinkClick()">Spirits</a>
                <a [routerLink]="['/liqueurs-cordial']" (click)="onLinkClick()">Liqueurs & Cordials</a>
                <a [routerLink]="['/rice-based-alcohol']" (click)="onLinkClick()">Rice Based Alcohols</a>
                <a [routerLink]="['/search']" (click)="onLinkClick()">Search</a>
            </div>
        </div>
        <a [routerLink]="['/about']" class="about" (click)="onLinkClick()">ABOUT</a>
        
        <!-- Conditional display based on isLoggedIn state -->
        <a *ngIf="!isLoggedIn" [routerLink]="['/login-signup']" class="login" (click)="onLinkClick()">LOGIN/SIGNUP</a>
        <a *ngIf="isLoggedIn" [routerLink]="['/account']" class="account" (click)="onLinkClick()">ACCOUNT</a>
    </nav>
</div>

// src/components/global/Header.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { auth } from '../../firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { useTheme } from '../../context/ThemeContext';
import './Header.css';

export default function Header() {
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const { theme, toggleTheme } = useTheme();

    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, user => {
            setIsLoggedIn(!!user);
        });
        return unsubscribe;
    }, []);

    const onLinkClick = () => {
        window.scrollTo(0, 0);
    };

    return (
        <div className="header" id="myheader">
            <div className="logo-title-container">
                <Link to="/main" onClick={onLinkClick}>
                    <h1 className="title">ALHOCOOL</h1>
                </Link>
            </div>
            <nav className="nav-links">
                <div className="explore-dropdown">
                    <button className="explore-button" disabled>EXPLORE</button>
                    <div className="dropdown-content">
                        <Link to="/beer" onClick={onLinkClick}>Beers</Link>
                        <Link to="/wine" onClick={onLinkClick}>Wines</Link>
                        <Link to="/spirit" onClick={onLinkClick}>Spirits</Link>
                        <Link to="/liqueurs-cordial" onClick={onLinkClick}>Liqueurs & Cordials</Link>
                        <Link to="/rice-based-alcohol" onClick={onLinkClick}>Rice Based Alcohols</Link>
                        <Link to="/search" onClick={onLinkClick}>Search</Link>
                    </div>
                </div>
                <Link to="/about" className="about" onClick={onLinkClick}>ABOUT</Link>
                
                {!isLoggedIn && <Link to="/login-signup" className="login" onClick={onLinkClick}>LOGIN/SIGNUP</Link>}
                {isLoggedIn && <Link to="/account" className="account" onClick={onLinkClick}>ACCOUNT</Link>}

                <button className="theme-toggle" onClick={toggleTheme}>
                  {theme === 'light' ? '🌙' : '☀️'}
                </button>
            </nav>
        </div>
    );
}
